/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.lexer;

import java.io.*;
import br.com.ufs.pascalito.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                                case 0: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteger(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBoolean(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArray(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThen(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCase(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOf(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBegin(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnd(text, line, pos); }
    Token new14(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProgram(text, line, pos); }
    Token new15(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(text, line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstBooleana(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoEVirgula(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoPonto(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreParenteses(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaParenteses(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreColchete(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaColchete(line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNum(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new30(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstString(text, line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOperadorRelacional(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAdicao(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSubtracao(line, pos); }
    Token new34(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(text, line, pos); }
    Token new35(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(text, line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOperadorMultiplicativo(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentLinha(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentBloco(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentBlocoFim(line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentBlocoCorpo(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAsterico(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarra(line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {39, 39, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {65, 65, 20}, {66, 66, 21}, {67, 67, 22}, {68, 68, 23}, {69, 69, 24}, {70, 70, 25}, {71, 72, 23}, {73, 73, 26}, {74, 76, 23}, {77, 77, 27}, {78, 78, 28}, {79, 79, 29}, {80, 80, 30}, {81, 81, 23}, {82, 82, 31}, {83, 83, 32}, {84, 84, 33}, {85, 85, 23}, {86, 86, 34}, {87, 87, 35}, {88, 90, 23}, {91, 91, 36}, {93, 93, 37}, {97, 97, 38}, {98, 98, 39}, {99, 99, 40}, {100, 100, 41}, {101, 101, 42}, {102, 102, 43}, {103, 104, 41}, {105, 105, 44}, {106, 108, 41}, {109, 109, 45}, {110, 110, 46}, {111, 111, 47}, {112, 112, 48}, {113, 113, 41}, {114, 114, 49}, {115, 115, 50}, {116, 116, 51}, {117, 117, 41}, {118, 118, 52}, {119, 119, 53}, {120, 122, 41}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 54}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 9, 55}, {11, 12, 55}, {14, 38, 55}, {39, 39, 56}, {40, 127, 55}, },
            {},
            {},
            {{47, 47, 57}, },
            {},
            {},
            {},
            {{46, 46, 58}, },
            {{42, 42, 59}, {47, 47, 60}, },
            {{46, 46, 61}, {48, 57, 62}, },
            {{61, 61, 63}, },
            {},
            {{61, 61, 64}, {62, 62, 65}, },
            {},
            {{61, 61, 66}, },
            {{48, 57, 67}, {65, 77, 68}, {78, 78, 69}, {79, 81, 68}, {82, 82, 70}, {83, 90, 68}, {97, 109, 71}, {110, 110, 72}, {111, 113, 71}, {114, 114, 73}, {115, 122, 71}, },
            {{48, 57, 67}, {65, 68, 68}, {69, 69, 74}, {70, 78, 68}, {79, 79, 75}, {80, 90, 68}, {97, 100, 71}, {101, 101, 76}, {102, 110, 71}, {111, 111, 77}, {112, 122, 71}, },
            {{48, 57, 67}, {65, 65, 78}, {66, 90, 68}, {97, 97, 79}, {98, 122, 71}, },
            {{48, 57, 67}, {65, 90, 68}, {97, 122, 71}, },
            {{48, 57, 67}, {65, 75, 68}, {76, 76, 80}, {77, 77, 68}, {78, 78, 81}, {79, 90, 68}, {97, 107, 71}, {108, 108, 82}, {109, 109, 71}, {110, 110, 83}, {111, 122, 71}, },
            {{48, 57, 67}, {65, 65, 84}, {66, 78, 68}, {79, 79, 85}, {80, 90, 68}, {97, 97, 86}, {98, 110, 71}, {111, 111, 87}, {112, 122, 71}, },
            {{48, 57, 67}, {65, 69, 68}, {70, 70, 88}, {71, 77, 68}, {78, 78, 89}, {79, 90, 68}, {97, 101, 71}, {102, 102, 90}, {103, 109, 71}, {110, 110, 91}, {111, 122, 71}, },
            {{48, 57, 67}, {65, 78, 68}, {79, 79, 92}, {80, 90, 68}, {97, 110, 71}, {111, 111, 93}, {112, 122, 71}, },
            {{48, 78, -29}, {79, 79, 94}, {80, 110, -29}, {111, 111, 95}, {112, 122, 71}, },
            {{48, 69, -28}, {70, 70, 96}, {71, 81, 68}, {82, 82, 97}, {83, 90, 68}, {97, 101, 71}, {102, 102, 98}, {103, 113, 71}, {114, 114, 99}, {115, 122, 71}, },
            {{48, 57, 67}, {65, 81, 68}, {82, 82, 100}, {83, 90, 68}, {97, 113, 71}, {114, 114, 101}, {115, 122, 71}, },
            {{48, 68, -23}, {69, 69, 102}, {70, 90, 68}, {97, 100, 71}, {101, 101, 103}, {102, 122, 71}, },
            {{48, 57, 67}, {65, 83, 68}, {84, 84, 104}, {85, 90, 68}, {97, 115, 71}, {116, 116, 105}, {117, 122, 71}, },
            {{48, 57, 67}, {65, 71, 68}, {72, 72, 106}, {73, 81, 68}, {82, 82, 107}, {83, 90, 68}, {97, 103, 71}, {104, 104, 108}, {105, 113, 71}, {114, 114, 109}, {115, 122, 71}, },
            {{48, 57, 67}, {65, 65, 110}, {66, 90, 68}, {97, 97, 111}, {98, 122, 71}, },
            {{48, 71, -35}, {72, 72, 112}, {73, 90, 68}, {97, 103, 71}, {104, 104, 113}, {105, 122, 71}, },
            {},
            {},
            {{48, 122, -22}, },
            {{48, 122, -23}, },
            {{48, 122, -24}, },
            {{48, 122, -25}, },
            {{48, 122, -26}, },
            {{48, 122, -27}, },
            {{48, 122, -28}, },
            {{48, 122, -29}, },
            {{48, 122, -30}, },
            {{48, 122, -31}, },
            {{48, 122, -32}, },
            {{48, 122, -33}, },
            {{48, 122, -34}, },
            {{48, 122, -35}, },
            {{48, 122, -36}, },
            {{48, 122, -37}, },
            {{9, 32, -2}, },
            {{0, 127, -7}, },
            {},
            {},
            {},
            {},
            {{0, 9, 114}, {10, 10, 115}, {11, 12, 114}, {13, 13, 116}, {14, 127, 114}, },
            {{48, 57, 117}, },
            {{46, 57, -16}, },
            {},
            {},
            {},
            {},
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 57, 67}, {65, 67, 68}, {68, 68, 118}, {69, 90, 68}, {97, 99, 71}, {100, 100, 119}, {101, 122, 71}, },
            {{48, 81, -32}, {82, 82, 120}, {83, 113, -32}, {114, 114, 121}, {115, 122, 71}, },
            {{48, 122, -25}, },
            {{48, 122, -71}, },
            {{48, 122, -72}, },
            {{48, 57, 67}, {65, 70, 68}, {71, 71, 122}, {72, 90, 68}, {97, 102, 71}, {103, 103, 123}, {104, 122, 71}, },
            {{48, 78, -29}, {79, 79, 124}, {80, 110, -29}, {111, 111, 125}, {112, 122, 71}, },
            {{48, 122, -76}, },
            {{48, 122, -77}, },
            {{48, 57, 67}, {65, 82, 68}, {83, 83, 126}, {84, 90, 68}, {97, 114, 71}, {115, 115, 127}, {116, 122, 71}, },
            {{48, 122, -80}, },
            {{48, 82, -80}, {83, 83, 128}, {84, 114, -80}, {115, 115, 129}, {116, 122, 71}, },
            {{48, 67, -71}, {68, 68, 130}, {69, 99, -71}, {100, 100, 131}, {101, 122, 71}, },
            {{48, 122, -82}, },
            {{48, 122, -83}, },
            {{48, 75, -26}, {76, 76, 132}, {77, 90, 68}, {97, 107, 71}, {108, 108, 133}, {109, 122, 71}, },
            {{48, 81, -32}, {82, 82, 134}, {83, 113, -32}, {114, 114, 135}, {115, 122, 71}, },
            {{48, 122, -86}, },
            {{48, 122, -87}, },
            {{48, 122, -25}, },
            {{48, 83, -34}, {84, 84, 136}, {85, 115, -34}, {116, 116, 137}, {117, 122, 71}, },
            {{48, 122, -25}, },
            {{48, 122, -91}, },
            {{48, 67, -71}, {68, 68, 138}, {69, 99, -71}, {100, 100, 139}, {101, 122, 71}, },
            {{48, 122, -94}, },
            {{48, 83, -34}, {84, 84, 140}, {85, 115, -34}, {116, 116, 141}, {117, 122, 71}, },
            {{48, 122, -96}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 78, -29}, {79, 79, 142}, {80, 110, -29}, {111, 111, 143}, {112, 122, 71}, },
            {{48, 122, -102}, },
            {{48, 57, 67}, {65, 65, 144}, {66, 90, 68}, {97, 97, 145}, {98, 122, 71}, },
            {{48, 122, -104}, },
            {{48, 81, -32}, {82, 82, 146}, {83, 113, -32}, {114, 114, 147}, {115, 122, 71}, },
            {{48, 122, -106}, },
            {{48, 68, -23}, {69, 69, 148}, {70, 100, -33}, {101, 101, 149}, {102, 122, 71}, },
            {{48, 57, 67}, {65, 84, 68}, {85, 85, 150}, {86, 90, 68}, {97, 116, 71}, {117, 117, 151}, {118, 122, 71}, },
            {{48, 122, -108}, },
            {{48, 122, -109}, },
            {{48, 81, -32}, {82, 82, 152}, {83, 113, -32}, {114, 114, 153}, {115, 122, 71}, },
            {{48, 122, -112}, },
            {{48, 57, 67}, {65, 72, 68}, {73, 73, 154}, {74, 90, 68}, {97, 104, 71}, {105, 105, 155}, {106, 122, 71}, },
            {{48, 122, -114}, },
            {{0, 127, -62}, },
            {},
            {{10, 10, 156}, },
            {{48, 57, 157}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 57, 67}, {65, 65, 158}, {66, 90, 68}, {97, 97, 159}, {98, 122, 71}, },
            {{48, 122, -122}, },
            {{48, 72, -114}, {73, 73, 160}, {74, 104, -114}, {105, 105, 161}, {106, 122, 71}, },
            {{48, 122, -124}, },
            {{48, 75, -26}, {76, 76, 162}, {77, 107, -86}, {108, 108, 163}, {109, 122, 71}, },
            {{48, 122, -126}, },
            {{48, 68, -23}, {69, 69, 164}, {70, 100, -33}, {101, 101, 165}, {102, 122, 71}, },
            {{48, 122, -128}, },
            {{48, 68, -23}, {69, 69, 166}, {70, 100, -33}, {101, 101, 167}, {102, 122, 71}, },
            {{48, 122, -130}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 82, -80}, {83, 83, 168}, {84, 114, -80}, {115, 115, 169}, {116, 122, 71}, },
            {{48, 122, -134}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 68, -23}, {69, 69, 170}, {70, 100, -33}, {101, 101, 171}, {102, 122, 71}, },
            {{48, 122, -138}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 70, -76}, {71, 71, 172}, {72, 102, -76}, {103, 103, 173}, {104, 122, 71}, },
            {{48, 122, -144}, },
            {{48, 75, -26}, {76, 76, 174}, {77, 107, -86}, {108, 108, 175}, {109, 122, 71}, },
            {{48, 122, -146}, },
            {{48, 72, -114}, {73, 73, 176}, {74, 104, -114}, {105, 105, 177}, {106, 122, 71}, },
            {{48, 122, -148}, },
            {{48, 77, -22}, {78, 78, 178}, {79, 90, 68}, {97, 109, 71}, {110, 110, 179}, {111, 122, 71}, },
            {{48, 122, -150}, },
            {{48, 68, -23}, {69, 69, 180}, {70, 100, -33}, {101, 101, 181}, {102, 122, 71}, },
            {{48, 122, -152}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 75, -26}, {76, 76, 182}, {77, 107, -86}, {108, 108, 183}, {109, 122, 71}, },
            {{48, 122, -156}, },
            {},
            {{48, 57, 157}, },
            {{48, 57, 67}, {65, 88, 68}, {89, 89, 184}, {90, 90, 68}, {97, 120, 71}, {121, 121, 185}, {122, 122, 71}, },
            {{48, 122, -160}, },
            {{48, 77, -22}, {78, 78, 186}, {79, 109, -150}, {110, 110, 187}, {111, 122, 71}, },
            {{48, 122, -162}, },
            {{48, 68, -23}, {69, 69, 188}, {70, 100, -33}, {101, 101, 189}, {102, 122, 71}, },
            {{48, 122, -164}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 68, -23}, {69, 69, 190}, {70, 100, -33}, {101, 101, 191}, {102, 122, 71}, },
            {{48, 122, -170}, },
            {{48, 70, -76}, {71, 71, 192}, {72, 102, -76}, {103, 103, 193}, {104, 122, 71}, },
            {{48, 122, -172}, },
            {{48, 81, -32}, {82, 82, 194}, {83, 113, -32}, {114, 114, 195}, {115, 122, 71}, },
            {{48, 122, -174}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 77, -22}, {78, 78, 196}, {79, 109, -150}, {110, 110, 197}, {111, 122, 71}, },
            {{48, 122, -178}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 68, -23}, {69, 69, 198}, {70, 100, -33}, {101, 101, 199}, {102, 122, 71}, },
            {{48, 122, -184}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 57, 67}, {65, 65, 200}, {66, 90, 68}, {97, 97, 201}, {98, 122, 71}, },
            {{48, 122, -190}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 68, -23}, {69, 69, 202}, {70, 100, -33}, {101, 101, 203}, {102, 122, 71}, },
            {{48, 122, -194}, },
            {{48, 57, 67}, {65, 65, 204}, {66, 90, 68}, {97, 97, 205}, {98, 122, 71}, },
            {{48, 122, -196}, },
            {{48, 70, -76}, {71, 71, 206}, {72, 102, -76}, {103, 103, 207}, {104, 122, 71}, },
            {{48, 122, -198}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 77, -22}, {78, 78, 208}, {79, 109, -150}, {110, 110, 209}, {111, 122, 71}, },
            {{48, 122, -202}, },
            {{48, 81, -32}, {82, 82, 210}, {83, 113, -32}, {114, 114, 211}, {115, 122, 71}, },
            {{48, 122, -204}, },
            {{48, 57, 67}, {65, 76, 68}, {77, 77, 212}, {78, 90, 68}, {97, 108, 71}, {109, 109, 213}, {110, 122, 71}, },
            {{48, 122, -206}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
        }
        { // COMMENT
            {{0, 41, 1}, {42, 42, 2}, {43, 46, 1}, {47, 47, 3}, {48, 127, 1}, },
            {{0, 41, 1}, {43, 46, 1}, {48, 127, 1}, },
            {{47, 47, 4}, },
            {{42, 42, 5}, },
            {},
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 29, 29, 29, 29, -1, 21, 22, 36, 32, 23, 33, 19, 36, 28, 25, 18, 31, 31, 31, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 26, 27, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 29, -1, 30, 39, 20, 38, -1, -1, 28, 24, 31, 31, 31, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 5, 17, 5, 17, 17, 17, 17, 17, 11, 17, 11, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, -1, 37, 37, 28, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 13, 13, 17, 17, 9, 9, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 15, 15, 17, 17, 37, 28, 17, 17, 17, 17, 17, 17, 10, 10, 7, 7, 17, 17, 17, 17, 17, 17, 2, 2, 17, 17, 6, 6, 16, 16, 17, 17, 4, 4, 12, 12, 17, 17, 16, 16, 17, 17, 17, 17, 17, 17, 8, 8, 17, 17, 17, 17, 17, 17, 1, 1, 3, 3, 0, 0, 14, 14, },
        // COMMENT
        {40, 40, 41, 42, 39, 38, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMMENT = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
