/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AArrayDenotadorTipo extends PDenotadorTipo
{
    private PTipoArray _tipoArray_;

    public AArrayDenotadorTipo()
    {
        // Constructor
    }

    public AArrayDenotadorTipo(
        @SuppressWarnings("hiding") PTipoArray _tipoArray_)
    {
        // Constructor
        setTipoArray(_tipoArray_);

    }

    @Override
    public Object clone()
    {
        return new AArrayDenotadorTipo(
            cloneNode(this._tipoArray_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayDenotadorTipo(this);
    }

    public PTipoArray getTipoArray()
    {
        return this._tipoArray_;
    }

    public void setTipoArray(PTipoArray node)
    {
        if(this._tipoArray_ != null)
        {
            this._tipoArray_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoArray_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoArray_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoArray_ == child)
        {
            this._tipoArray_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoArray_ == oldChild)
        {
            setTipoArray((PTipoArray) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
