/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import java.util.*;
import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ABloco extends PBloco
{
    private final LinkedList<TNum> _num_ = new LinkedList<TNum>();

    public ABloco()
    {
        // Constructor
    }

    public ABloco(
        @SuppressWarnings("hiding") List<?> _num_)
    {
        // Constructor
        setNum(_num_);

    }

    @Override
    public Object clone()
    {
        return new ABloco(
            cloneList(this._num_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloco(this);
    }

    public LinkedList<TNum> getNum()
    {
        return this._num_;
    }

    public void setNum(List<?> list)
    {
        for(TNum e : this._num_)
        {
            e.parent(null);
        }
        this._num_.clear();

        for(Object obj_e : list)
        {
            TNum e = (TNum) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._num_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._num_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._num_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TNum> i = this._num_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TNum) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
