/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ACabecalhoFuncao extends PCabecalhoFuncao
{
    private TFunction _function_;
    private TIdentificador _identificador_;
    private PParametrosFormais _parametrosFormais_;
    private TDoisPontos _doisPontos_;
    private PTipoResultado _tipoResultado_;

    public ACabecalhoFuncao()
    {
        // Constructor
    }

    public ACabecalhoFuncao(
        @SuppressWarnings("hiding") TFunction _function_,
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") PParametrosFormais _parametrosFormais_,
        @SuppressWarnings("hiding") TDoisPontos _doisPontos_,
        @SuppressWarnings("hiding") PTipoResultado _tipoResultado_)
    {
        // Constructor
        setFunction(_function_);

        setIdentificador(_identificador_);

        setParametrosFormais(_parametrosFormais_);

        setDoisPontos(_doisPontos_);

        setTipoResultado(_tipoResultado_);

    }

    @Override
    public Object clone()
    {
        return new ACabecalhoFuncao(
            cloneNode(this._function_),
            cloneNode(this._identificador_),
            cloneNode(this._parametrosFormais_),
            cloneNode(this._doisPontos_),
            cloneNode(this._tipoResultado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACabecalhoFuncao(this);
    }

    public TFunction getFunction()
    {
        return this._function_;
    }

    public void setFunction(TFunction node)
    {
        if(this._function_ != null)
        {
            this._function_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._function_ = node;
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public PParametrosFormais getParametrosFormais()
    {
        return this._parametrosFormais_;
    }

    public void setParametrosFormais(PParametrosFormais node)
    {
        if(this._parametrosFormais_ != null)
        {
            this._parametrosFormais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametrosFormais_ = node;
    }

    public TDoisPontos getDoisPontos()
    {
        return this._doisPontos_;
    }

    public void setDoisPontos(TDoisPontos node)
    {
        if(this._doisPontos_ != null)
        {
            this._doisPontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisPontos_ = node;
    }

    public PTipoResultado getTipoResultado()
    {
        return this._tipoResultado_;
    }

    public void setTipoResultado(PTipoResultado node)
    {
        if(this._tipoResultado_ != null)
        {
            this._tipoResultado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoResultado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._function_)
            + toString(this._identificador_)
            + toString(this._parametrosFormais_)
            + toString(this._doisPontos_)
            + toString(this._tipoResultado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._function_ == child)
        {
            this._function_ = null;
            return;
        }

        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._parametrosFormais_ == child)
        {
            this._parametrosFormais_ = null;
            return;
        }

        if(this._doisPontos_ == child)
        {
            this._doisPontos_ = null;
            return;
        }

        if(this._tipoResultado_ == child)
        {
            this._tipoResultado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._function_ == oldChild)
        {
            setFunction((TFunction) newChild);
            return;
        }

        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._parametrosFormais_ == oldChild)
        {
            setParametrosFormais((PParametrosFormais) newChild);
            return;
        }

        if(this._doisPontos_ == oldChild)
        {
            setDoisPontos((TDoisPontos) newChild);
            return;
        }

        if(this._tipoResultado_ == oldChild)
        {
            setTipoResultado((PTipoResultado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
