/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AConstanteSemSinalFator extends PFator
{
    private PConstanteSemSinal _constanteSemSinal_;

    public AConstanteSemSinalFator()
    {
        // Constructor
    }

    public AConstanteSemSinalFator(
        @SuppressWarnings("hiding") PConstanteSemSinal _constanteSemSinal_)
    {
        // Constructor
        setConstanteSemSinal(_constanteSemSinal_);

    }

    @Override
    public Object clone()
    {
        return new AConstanteSemSinalFator(
            cloneNode(this._constanteSemSinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstanteSemSinalFator(this);
    }

    public PConstanteSemSinal getConstanteSemSinal()
    {
        return this._constanteSemSinal_;
    }

    public void setConstanteSemSinal(PConstanteSemSinal node)
    {
        if(this._constanteSemSinal_ != null)
        {
            this._constanteSemSinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constanteSemSinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constanteSemSinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constanteSemSinal_ == child)
        {
            this._constanteSemSinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constanteSemSinal_ == oldChild)
        {
            setConstanteSemSinal((PConstanteSemSinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
