/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoesProcFuncoes extends PDeclaracoesProcFuncoes
{
    private PDeclaracaoProcFuncoes _declaracaoProcFuncoes_;

    public ADeclaracoesProcFuncoes()
    {
        // Constructor
    }

    public ADeclaracoesProcFuncoes(
        @SuppressWarnings("hiding") PDeclaracaoProcFuncoes _declaracaoProcFuncoes_)
    {
        // Constructor
        setDeclaracaoProcFuncoes(_declaracaoProcFuncoes_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoesProcFuncoes(
            cloneNode(this._declaracaoProcFuncoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoesProcFuncoes(this);
    }

    public PDeclaracaoProcFuncoes getDeclaracaoProcFuncoes()
    {
        return this._declaracaoProcFuncoes_;
    }

    public void setDeclaracaoProcFuncoes(PDeclaracaoProcFuncoes node)
    {
        if(this._declaracaoProcFuncoes_ != null)
        {
            this._declaracaoProcFuncoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoProcFuncoes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoProcFuncoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoProcFuncoes_ == child)
        {
            this._declaracaoProcFuncoes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoProcFuncoes_ == oldChild)
        {
            setDeclaracaoProcFuncoes((PDeclaracaoProcFuncoes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
