/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoFuncao extends PDeclaracaoFuncao
{
    private PCabecalhoFuncao _cabecalhoFuncao_;
    private TPontoEVirgula _pontoEVirgula_;
    private PBloco _bloco_;

    public ADeclaracaoFuncao()
    {
        // Constructor
    }

    public ADeclaracaoFuncao(
        @SuppressWarnings("hiding") PCabecalhoFuncao _cabecalhoFuncao_,
        @SuppressWarnings("hiding") TPontoEVirgula _pontoEVirgula_,
        @SuppressWarnings("hiding") PBloco _bloco_)
    {
        // Constructor
        setCabecalhoFuncao(_cabecalhoFuncao_);

        setPontoEVirgula(_pontoEVirgula_);

        setBloco(_bloco_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoFuncao(
            cloneNode(this._cabecalhoFuncao_),
            cloneNode(this._pontoEVirgula_),
            cloneNode(this._bloco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoFuncao(this);
    }

    public PCabecalhoFuncao getCabecalhoFuncao()
    {
        return this._cabecalhoFuncao_;
    }

    public void setCabecalhoFuncao(PCabecalhoFuncao node)
    {
        if(this._cabecalhoFuncao_ != null)
        {
            this._cabecalhoFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cabecalhoFuncao_ = node;
    }

    public TPontoEVirgula getPontoEVirgula()
    {
        return this._pontoEVirgula_;
    }

    public void setPontoEVirgula(TPontoEVirgula node)
    {
        if(this._pontoEVirgula_ != null)
        {
            this._pontoEVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEVirgula_ = node;
    }

    public PBloco getBloco()
    {
        return this._bloco_;
    }

    public void setBloco(PBloco node)
    {
        if(this._bloco_ != null)
        {
            this._bloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cabecalhoFuncao_)
            + toString(this._pontoEVirgula_)
            + toString(this._bloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cabecalhoFuncao_ == child)
        {
            this._cabecalhoFuncao_ = null;
            return;
        }

        if(this._pontoEVirgula_ == child)
        {
            this._pontoEVirgula_ = null;
            return;
        }

        if(this._bloco_ == child)
        {
            this._bloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cabecalhoFuncao_ == oldChild)
        {
            setCabecalhoFuncao((PCabecalhoFuncao) newChild);
            return;
        }

        if(this._pontoEVirgula_ == oldChild)
        {
            setPontoEVirgula((TPontoEVirgula) newChild);
            return;
        }

        if(this._bloco_ == oldChild)
        {
            setBloco((PBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
