/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ADefinicaoTipo extends PDefinicaoTipo
{
    private TIdentificador _identificador_;
    private TIgual _igual_;
    private PDenotadorTipo _denotadorTipo_;

    public ADefinicaoTipo()
    {
        // Constructor
    }

    public ADefinicaoTipo(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") TIgual _igual_,
        @SuppressWarnings("hiding") PDenotadorTipo _denotadorTipo_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setIgual(_igual_);

        setDenotadorTipo(_denotadorTipo_);

    }

    @Override
    public Object clone()
    {
        return new ADefinicaoTipo(
            cloneNode(this._identificador_),
            cloneNode(this._igual_),
            cloneNode(this._denotadorTipo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefinicaoTipo(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public TIgual getIgual()
    {
        return this._igual_;
    }

    public void setIgual(TIgual node)
    {
        if(this._igual_ != null)
        {
            this._igual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igual_ = node;
    }

    public PDenotadorTipo getDenotadorTipo()
    {
        return this._denotadorTipo_;
    }

    public void setDenotadorTipo(PDenotadorTipo node)
    {
        if(this._denotadorTipo_ != null)
        {
            this._denotadorTipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._denotadorTipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._igual_)
            + toString(this._denotadorTipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._igual_ == child)
        {
            this._igual_ = null;
            return;
        }

        if(this._denotadorTipo_ == child)
        {
            this._denotadorTipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._igual_ == oldChild)
        {
            setIgual((TIgual) newChild);
            return;
        }

        if(this._denotadorTipo_ == oldChild)
        {
            setDenotadorTipo((PDenotadorTipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
