/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AEstruturadaFechadaDefinicaoSentenca extends PDefinicaoSentenca
{
    private PDefinicaoSentencaEstruturadaFechada _definicaoSentencaEstruturadaFechada_;

    public AEstruturadaFechadaDefinicaoSentenca()
    {
        // Constructor
    }

    public AEstruturadaFechadaDefinicaoSentenca(
        @SuppressWarnings("hiding") PDefinicaoSentencaEstruturadaFechada _definicaoSentencaEstruturadaFechada_)
    {
        // Constructor
        setDefinicaoSentencaEstruturadaFechada(_definicaoSentencaEstruturadaFechada_);

    }

    @Override
    public Object clone()
    {
        return new AEstruturadaFechadaDefinicaoSentenca(
            cloneNode(this._definicaoSentencaEstruturadaFechada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEstruturadaFechadaDefinicaoSentenca(this);
    }

    public PDefinicaoSentencaEstruturadaFechada getDefinicaoSentencaEstruturadaFechada()
    {
        return this._definicaoSentencaEstruturadaFechada_;
    }

    public void setDefinicaoSentencaEstruturadaFechada(PDefinicaoSentencaEstruturadaFechada node)
    {
        if(this._definicaoSentencaEstruturadaFechada_ != null)
        {
            this._definicaoSentencaEstruturadaFechada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoSentencaEstruturadaFechada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definicaoSentencaEstruturadaFechada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definicaoSentencaEstruturadaFechada_ == child)
        {
            this._definicaoSentencaEstruturadaFechada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definicaoSentencaEstruturadaFechada_ == oldChild)
        {
            setDefinicaoSentencaEstruturadaFechada((PDefinicaoSentencaEstruturadaFechada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
