/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AEstruturadaSentencaWhile extends PSentencaWhile
{
    private TWhile _while_;
    private PExpressao _expressao_;
    private TDo _do_;
    private PDefinicaoSentencaEstruturada _definicaoSentencaEstruturada_;

    public AEstruturadaSentencaWhile()
    {
        // Constructor
    }

    public AEstruturadaSentencaWhile(
        @SuppressWarnings("hiding") TWhile _while_,
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PDefinicaoSentencaEstruturada _definicaoSentencaEstruturada_)
    {
        // Constructor
        setWhile(_while_);

        setExpressao(_expressao_);

        setDo(_do_);

        setDefinicaoSentencaEstruturada(_definicaoSentencaEstruturada_);

    }

    @Override
    public Object clone()
    {
        return new AEstruturadaSentencaWhile(
            cloneNode(this._while_),
            cloneNode(this._expressao_),
            cloneNode(this._do_),
            cloneNode(this._definicaoSentencaEstruturada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEstruturadaSentencaWhile(this);
    }

    public TWhile getWhile()
    {
        return this._while_;
    }

    public void setWhile(TWhile node)
    {
        if(this._while_ != null)
        {
            this._while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._while_ = node;
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PDefinicaoSentencaEstruturada getDefinicaoSentencaEstruturada()
    {
        return this._definicaoSentencaEstruturada_;
    }

    public void setDefinicaoSentencaEstruturada(PDefinicaoSentencaEstruturada node)
    {
        if(this._definicaoSentencaEstruturada_ != null)
        {
            this._definicaoSentencaEstruturada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoSentencaEstruturada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._while_)
            + toString(this._expressao_)
            + toString(this._do_)
            + toString(this._definicaoSentencaEstruturada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._while_ == child)
        {
            this._while_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._definicaoSentencaEstruturada_ == child)
        {
            this._definicaoSentencaEstruturada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._definicaoSentencaEstruturada_ == oldChild)
        {
            setDefinicaoSentencaEstruturada((PDefinicaoSentencaEstruturada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
