/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AEstruturadaSentenca extends PSentenca
{
    private PDefinicaoSentencaEstruturada _definicaoSentencaEstruturada_;

    public AEstruturadaSentenca()
    {
        // Constructor
    }

    public AEstruturadaSentenca(
        @SuppressWarnings("hiding") PDefinicaoSentencaEstruturada _definicaoSentencaEstruturada_)
    {
        // Constructor
        setDefinicaoSentencaEstruturada(_definicaoSentencaEstruturada_);

    }

    @Override
    public Object clone()
    {
        return new AEstruturadaSentenca(
            cloneNode(this._definicaoSentencaEstruturada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEstruturadaSentenca(this);
    }

    public PDefinicaoSentencaEstruturada getDefinicaoSentencaEstruturada()
    {
        return this._definicaoSentencaEstruturada_;
    }

    public void setDefinicaoSentencaEstruturada(PDefinicaoSentencaEstruturada node)
    {
        if(this._definicaoSentencaEstruturada_ != null)
        {
            this._definicaoSentencaEstruturada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoSentencaEstruturada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definicaoSentencaEstruturada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definicaoSentencaEstruturada_ == child)
        {
            this._definicaoSentencaEstruturada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definicaoSentencaEstruturada_ == oldChild)
        {
            setDefinicaoSentencaEstruturada((PDefinicaoSentencaEstruturada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
