/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoDeclaracaoProcFuncao extends PDeclaracaoProcFuncao
{
    private PDeclaracaoFuncao _declaracaoFuncao_;
    private TPontoEVirgula _pontoEVirgula_;

    public AFuncaoDeclaracaoProcFuncao()
    {
        // Constructor
    }

    public AFuncaoDeclaracaoProcFuncao(
        @SuppressWarnings("hiding") PDeclaracaoFuncao _declaracaoFuncao_,
        @SuppressWarnings("hiding") TPontoEVirgula _pontoEVirgula_)
    {
        // Constructor
        setDeclaracaoFuncao(_declaracaoFuncao_);

        setPontoEVirgula(_pontoEVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoDeclaracaoProcFuncao(
            cloneNode(this._declaracaoFuncao_),
            cloneNode(this._pontoEVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoDeclaracaoProcFuncao(this);
    }

    public PDeclaracaoFuncao getDeclaracaoFuncao()
    {
        return this._declaracaoFuncao_;
    }

    public void setDeclaracaoFuncao(PDeclaracaoFuncao node)
    {
        if(this._declaracaoFuncao_ != null)
        {
            this._declaracaoFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoFuncao_ = node;
    }

    public TPontoEVirgula getPontoEVirgula()
    {
        return this._pontoEVirgula_;
    }

    public void setPontoEVirgula(TPontoEVirgula node)
    {
        if(this._pontoEVirgula_ != null)
        {
            this._pontoEVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoFuncao_)
            + toString(this._pontoEVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoFuncao_ == child)
        {
            this._declaracaoFuncao_ = null;
            return;
        }

        if(this._pontoEVirgula_ == child)
        {
            this._pontoEVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoFuncao_ == oldChild)
        {
            setDeclaracaoFuncao((PDeclaracaoFuncao) newChild);
            return;
        }

        if(this._pontoEVirgula_ == oldChild)
        {
            setPontoEVirgula((TPontoEVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
