/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AGotoSentenca extends PSentenca
{
    private PNumeroSemSinal _numeroSemSinal_;

    public AGotoSentenca()
    {
        // Constructor
    }

    public AGotoSentenca(
        @SuppressWarnings("hiding") PNumeroSemSinal _numeroSemSinal_)
    {
        // Constructor
        setNumeroSemSinal(_numeroSemSinal_);

    }

    @Override
    public Object clone()
    {
        return new AGotoSentenca(
            cloneNode(this._numeroSemSinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGotoSentenca(this);
    }

    public PNumeroSemSinal getNumeroSemSinal()
    {
        return this._numeroSemSinal_;
    }

    public void setNumeroSemSinal(PNumeroSemSinal node)
    {
        if(this._numeroSemSinal_ != null)
        {
            this._numeroSemSinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeroSemSinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numeroSemSinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numeroSemSinal_ == child)
        {
            this._numeroSemSinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numeroSemSinal_ == oldChild)
        {
            setNumeroSemSinal((PNumeroSemSinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
