/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AMultiploTiposOrdinais extends PTiposOrdinais
{
    private PTiposOrdinais _tiposOrdinais_;
    private TVirgula _virgula_;
    private PTipoOrdinal _tipoOrdinal_;

    public AMultiploTiposOrdinais()
    {
        // Constructor
    }

    public AMultiploTiposOrdinais(
        @SuppressWarnings("hiding") PTiposOrdinais _tiposOrdinais_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PTipoOrdinal _tipoOrdinal_)
    {
        // Constructor
        setTiposOrdinais(_tiposOrdinais_);

        setVirgula(_virgula_);

        setTipoOrdinal(_tipoOrdinal_);

    }

    @Override
    public Object clone()
    {
        return new AMultiploTiposOrdinais(
            cloneNode(this._tiposOrdinais_),
            cloneNode(this._virgula_),
            cloneNode(this._tipoOrdinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiploTiposOrdinais(this);
    }

    public PTiposOrdinais getTiposOrdinais()
    {
        return this._tiposOrdinais_;
    }

    public void setTiposOrdinais(PTiposOrdinais node)
    {
        if(this._tiposOrdinais_ != null)
        {
            this._tiposOrdinais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tiposOrdinais_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PTipoOrdinal getTipoOrdinal()
    {
        return this._tipoOrdinal_;
    }

    public void setTipoOrdinal(PTipoOrdinal node)
    {
        if(this._tipoOrdinal_ != null)
        {
            this._tipoOrdinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoOrdinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tiposOrdinais_)
            + toString(this._virgula_)
            + toString(this._tipoOrdinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tiposOrdinais_ == child)
        {
            this._tiposOrdinais_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._tipoOrdinal_ == child)
        {
            this._tipoOrdinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tiposOrdinais_ == oldChild)
        {
            setTiposOrdinais((PTiposOrdinais) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._tipoOrdinal_ == oldChild)
        {
            setTipoOrdinal((PTipoOrdinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
