/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AMultiploDeclaracaoProcFuncoes extends PDeclaracaoProcFuncoes
{
    private PDeclaracaoProcFuncoes _declaracaoProcFuncoes_;
    private PDeclaracaoProcFuncao _declaracaoProcFuncao_;

    public AMultiploDeclaracaoProcFuncoes()
    {
        // Constructor
    }

    public AMultiploDeclaracaoProcFuncoes(
        @SuppressWarnings("hiding") PDeclaracaoProcFuncoes _declaracaoProcFuncoes_,
        @SuppressWarnings("hiding") PDeclaracaoProcFuncao _declaracaoProcFuncao_)
    {
        // Constructor
        setDeclaracaoProcFuncoes(_declaracaoProcFuncoes_);

        setDeclaracaoProcFuncao(_declaracaoProcFuncao_);

    }

    @Override
    public Object clone()
    {
        return new AMultiploDeclaracaoProcFuncoes(
            cloneNode(this._declaracaoProcFuncoes_),
            cloneNode(this._declaracaoProcFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiploDeclaracaoProcFuncoes(this);
    }

    public PDeclaracaoProcFuncoes getDeclaracaoProcFuncoes()
    {
        return this._declaracaoProcFuncoes_;
    }

    public void setDeclaracaoProcFuncoes(PDeclaracaoProcFuncoes node)
    {
        if(this._declaracaoProcFuncoes_ != null)
        {
            this._declaracaoProcFuncoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoProcFuncoes_ = node;
    }

    public PDeclaracaoProcFuncao getDeclaracaoProcFuncao()
    {
        return this._declaracaoProcFuncao_;
    }

    public void setDeclaracaoProcFuncao(PDeclaracaoProcFuncao node)
    {
        if(this._declaracaoProcFuncao_ != null)
        {
            this._declaracaoProcFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoProcFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoProcFuncoes_)
            + toString(this._declaracaoProcFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoProcFuncoes_ == child)
        {
            this._declaracaoProcFuncoes_ = null;
            return;
        }

        if(this._declaracaoProcFuncao_ == child)
        {
            this._declaracaoProcFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoProcFuncoes_ == oldChild)
        {
            setDeclaracaoProcFuncoes((PDeclaracaoProcFuncoes) newChild);
            return;
        }

        if(this._declaracaoProcFuncao_ == oldChild)
        {
            setDeclaracaoProcFuncao((PDeclaracaoProcFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
