/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AMultiploExpressaoSimples extends PExpressaoSimples
{
    private PExpressaoSimples _expressaoSimples_;
    private POperadorAditivo _operadorAditivo_;
    private PTermo _termo_;

    public AMultiploExpressaoSimples()
    {
        // Constructor
    }

    public AMultiploExpressaoSimples(
        @SuppressWarnings("hiding") PExpressaoSimples _expressaoSimples_,
        @SuppressWarnings("hiding") POperadorAditivo _operadorAditivo_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setExpressaoSimples(_expressaoSimples_);

        setOperadorAditivo(_operadorAditivo_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new AMultiploExpressaoSimples(
            cloneNode(this._expressaoSimples_),
            cloneNode(this._operadorAditivo_),
            cloneNode(this._termo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiploExpressaoSimples(this);
    }

    public PExpressaoSimples getExpressaoSimples()
    {
        return this._expressaoSimples_;
    }

    public void setExpressaoSimples(PExpressaoSimples node)
    {
        if(this._expressaoSimples_ != null)
        {
            this._expressaoSimples_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoSimples_ = node;
    }

    public POperadorAditivo getOperadorAditivo()
    {
        return this._operadorAditivo_;
    }

    public void setOperadorAditivo(POperadorAditivo node)
    {
        if(this._operadorAditivo_ != null)
        {
            this._operadorAditivo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operadorAditivo_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoSimples_)
            + toString(this._operadorAditivo_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoSimples_ == child)
        {
            this._expressaoSimples_ = null;
            return;
        }

        if(this._operadorAditivo_ == child)
        {
            this._operadorAditivo_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoSimples_ == oldChild)
        {
            setExpressaoSimples((PExpressaoSimples) newChild);
            return;
        }

        if(this._operadorAditivo_ == oldChild)
        {
            setOperadorAditivo((POperadorAditivo) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
