/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AMultiploDefinicaoParametrosReais extends PDefinicaoParametrosReais
{
    private PDefinicaoParametrosReais _definicaoParametrosReais_;
    private TVirgula _virgula_;
    private PExpressao _expressao_;

    public AMultiploDefinicaoParametrosReais()
    {
        // Constructor
    }

    public AMultiploDefinicaoParametrosReais(
        @SuppressWarnings("hiding") PDefinicaoParametrosReais _definicaoParametrosReais_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PExpressao _expressao_)
    {
        // Constructor
        setDefinicaoParametrosReais(_definicaoParametrosReais_);

        setVirgula(_virgula_);

        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new AMultiploDefinicaoParametrosReais(
            cloneNode(this._definicaoParametrosReais_),
            cloneNode(this._virgula_),
            cloneNode(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiploDefinicaoParametrosReais(this);
    }

    public PDefinicaoParametrosReais getDefinicaoParametrosReais()
    {
        return this._definicaoParametrosReais_;
    }

    public void setDefinicaoParametrosReais(PDefinicaoParametrosReais node)
    {
        if(this._definicaoParametrosReais_ != null)
        {
            this._definicaoParametrosReais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoParametrosReais_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definicaoParametrosReais_)
            + toString(this._virgula_)
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definicaoParametrosReais_ == child)
        {
            this._definicaoParametrosReais_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definicaoParametrosReais_ == oldChild)
        {
            setDefinicaoParametrosReais((PDefinicaoParametrosReais) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
