/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ANumeroConstante extends PConstante
{
    private TSinal _sinal_;
    private PConstNumeroSemSinal _constNumeroSemSinal_;

    public ANumeroConstante()
    {
        // Constructor
    }

    public ANumeroConstante(
        @SuppressWarnings("hiding") TSinal _sinal_,
        @SuppressWarnings("hiding") PConstNumeroSemSinal _constNumeroSemSinal_)
    {
        // Constructor
        setSinal(_sinal_);

        setConstNumeroSemSinal(_constNumeroSemSinal_);

    }

    @Override
    public Object clone()
    {
        return new ANumeroConstante(
            cloneNode(this._sinal_),
            cloneNode(this._constNumeroSemSinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeroConstante(this);
    }

    public TSinal getSinal()
    {
        return this._sinal_;
    }

    public void setSinal(TSinal node)
    {
        if(this._sinal_ != null)
        {
            this._sinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinal_ = node;
    }

    public PConstNumeroSemSinal getConstNumeroSemSinal()
    {
        return this._constNumeroSemSinal_;
    }

    public void setConstNumeroSemSinal(PConstNumeroSemSinal node)
    {
        if(this._constNumeroSemSinal_ != null)
        {
            this._constNumeroSemSinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constNumeroSemSinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sinal_)
            + toString(this._constNumeroSemSinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sinal_ == child)
        {
            this._sinal_ = null;
            return;
        }

        if(this._constNumeroSemSinal_ == child)
        {
            this._constNumeroSemSinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sinal_ == oldChild)
        {
            setSinal((TSinal) newChild);
            return;
        }

        if(this._constNumeroSemSinal_ == oldChild)
        {
            setConstNumeroSemSinal((PConstNumeroSemSinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
