/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AOrdinalTipoResultado extends PTipoResultado
{
    private PIdentificadorTipoOrdinal _identificadorTipoOrdinal_;

    public AOrdinalTipoResultado()
    {
        // Constructor
    }

    public AOrdinalTipoResultado(
        @SuppressWarnings("hiding") PIdentificadorTipoOrdinal _identificadorTipoOrdinal_)
    {
        // Constructor
        setIdentificadorTipoOrdinal(_identificadorTipoOrdinal_);

    }

    @Override
    public Object clone()
    {
        return new AOrdinalTipoResultado(
            cloneNode(this._identificadorTipoOrdinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrdinalTipoResultado(this);
    }

    public PIdentificadorTipoOrdinal getIdentificadorTipoOrdinal()
    {
        return this._identificadorTipoOrdinal_;
    }

    public void setIdentificadorTipoOrdinal(PIdentificadorTipoOrdinal node)
    {
        if(this._identificadorTipoOrdinal_ != null)
        {
            this._identificadorTipoOrdinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificadorTipoOrdinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificadorTipoOrdinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificadorTipoOrdinal_ == child)
        {
            this._identificadorTipoOrdinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificadorTipoOrdinal_ == oldChild)
        {
            setIdentificadorTipoOrdinal((PIdentificadorTipoOrdinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
