/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosFormais extends PParametrosFormais
{
    private TAbreParenteses _abreParenteses_;
    private PSecaoParametrosFormais _secaoParametrosFormais_;
    private TFechaParenteses _fechaParenteses_;

    public AParametrosFormais()
    {
        // Constructor
    }

    public AParametrosFormais(
        @SuppressWarnings("hiding") TAbreParenteses _abreParenteses_,
        @SuppressWarnings("hiding") PSecaoParametrosFormais _secaoParametrosFormais_,
        @SuppressWarnings("hiding") TFechaParenteses _fechaParenteses_)
    {
        // Constructor
        setAbreParenteses(_abreParenteses_);

        setSecaoParametrosFormais(_secaoParametrosFormais_);

        setFechaParenteses(_fechaParenteses_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosFormais(
            cloneNode(this._abreParenteses_),
            cloneNode(this._secaoParametrosFormais_),
            cloneNode(this._fechaParenteses_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosFormais(this);
    }

    public TAbreParenteses getAbreParenteses()
    {
        return this._abreParenteses_;
    }

    public void setAbreParenteses(TAbreParenteses node)
    {
        if(this._abreParenteses_ != null)
        {
            this._abreParenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParenteses_ = node;
    }

    public PSecaoParametrosFormais getSecaoParametrosFormais()
    {
        return this._secaoParametrosFormais_;
    }

    public void setSecaoParametrosFormais(PSecaoParametrosFormais node)
    {
        if(this._secaoParametrosFormais_ != null)
        {
            this._secaoParametrosFormais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secaoParametrosFormais_ = node;
    }

    public TFechaParenteses getFechaParenteses()
    {
        return this._fechaParenteses_;
    }

    public void setFechaParenteses(TFechaParenteses node)
    {
        if(this._fechaParenteses_ != null)
        {
            this._fechaParenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParenteses_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abreParenteses_)
            + toString(this._secaoParametrosFormais_)
            + toString(this._fechaParenteses_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abreParenteses_ == child)
        {
            this._abreParenteses_ = null;
            return;
        }

        if(this._secaoParametrosFormais_ == child)
        {
            this._secaoParametrosFormais_ = null;
            return;
        }

        if(this._fechaParenteses_ == child)
        {
            this._fechaParenteses_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abreParenteses_ == oldChild)
        {
            setAbreParenteses((TAbreParenteses) newChild);
            return;
        }

        if(this._secaoParametrosFormais_ == oldChild)
        {
            setSecaoParametrosFormais((PSecaoParametrosFormais) newChild);
            return;
        }

        if(this._fechaParenteses_ == oldChild)
        {
            setFechaParenteses((TFechaParenteses) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
