/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AProcedureDeclaracaoProcFuncao extends PDeclaracaoProcFuncao
{
    private PDeclaracaoProcedure _declaracaoProcedure_;
    private TPontoEVirgula _pontoEVirgula_;

    public AProcedureDeclaracaoProcFuncao()
    {
        // Constructor
    }

    public AProcedureDeclaracaoProcFuncao(
        @SuppressWarnings("hiding") PDeclaracaoProcedure _declaracaoProcedure_,
        @SuppressWarnings("hiding") TPontoEVirgula _pontoEVirgula_)
    {
        // Constructor
        setDeclaracaoProcedure(_declaracaoProcedure_);

        setPontoEVirgula(_pontoEVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AProcedureDeclaracaoProcFuncao(
            cloneNode(this._declaracaoProcedure_),
            cloneNode(this._pontoEVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedureDeclaracaoProcFuncao(this);
    }

    public PDeclaracaoProcedure getDeclaracaoProcedure()
    {
        return this._declaracaoProcedure_;
    }

    public void setDeclaracaoProcedure(PDeclaracaoProcedure node)
    {
        if(this._declaracaoProcedure_ != null)
        {
            this._declaracaoProcedure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoProcedure_ = node;
    }

    public TPontoEVirgula getPontoEVirgula()
    {
        return this._pontoEVirgula_;
    }

    public void setPontoEVirgula(TPontoEVirgula node)
    {
        if(this._pontoEVirgula_ != null)
        {
            this._pontoEVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoEVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoProcedure_)
            + toString(this._pontoEVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoProcedure_ == child)
        {
            this._declaracaoProcedure_ = null;
            return;
        }

        if(this._pontoEVirgula_ == child)
        {
            this._pontoEVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoProcedure_ == oldChild)
        {
            setDeclaracaoProcedure((PDeclaracaoProcedure) newChild);
            return;
        }

        if(this._pontoEVirgula_ == oldChild)
        {
            setPontoEVirgula((TPontoEVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
