/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AProcedureSentencaSimples extends PSentencaSimples
{
    private PSentencaProcedure _sentencaProcedure_;

    public AProcedureSentencaSimples()
    {
        // Constructor
    }

    public AProcedureSentencaSimples(
        @SuppressWarnings("hiding") PSentencaProcedure _sentencaProcedure_)
    {
        // Constructor
        setSentencaProcedure(_sentencaProcedure_);

    }

    @Override
    public Object clone()
    {
        return new AProcedureSentencaSimples(
            cloneNode(this._sentencaProcedure_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedureSentencaSimples(this);
    }

    public PSentencaProcedure getSentencaProcedure()
    {
        return this._sentencaProcedure_;
    }

    public void setSentencaProcedure(PSentencaProcedure node)
    {
        if(this._sentencaProcedure_ != null)
        {
            this._sentencaProcedure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sentencaProcedure_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sentencaProcedure_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sentencaProcedure_ == child)
        {
            this._sentencaProcedure_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sentencaProcedure_ == oldChild)
        {
            setSentencaProcedure((PSentencaProcedure) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
