/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import java.util.*;
import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AProcedureSentenca extends PSentenca
{
    private PString _string_;
    private final LinkedList<PExpressao> _expressao_ = new LinkedList<PExpressao>();

    public AProcedureSentenca()
    {
        // Constructor
    }

    public AProcedureSentenca(
        @SuppressWarnings("hiding") PString _string_,
        @SuppressWarnings("hiding") List<?> _expressao_)
    {
        // Constructor
        setString(_string_);

        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new AProcedureSentenca(
            cloneNode(this._string_),
            cloneList(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedureSentenca(this);
    }

    public PString getString()
    {
        return this._string_;
    }

    public void setString(PString node)
    {
        if(this._string_ != null)
        {
            this._string_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._string_ = node;
    }

    public LinkedList<PExpressao> getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(List<?> list)
    {
        for(PExpressao e : this._expressao_)
        {
            e.parent(null);
        }
        this._expressao_.clear();

        for(Object obj_e : list)
        {
            PExpressao e = (PExpressao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expressao_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._string_)
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._string_ == child)
        {
            this._string_ = null;
            return;
        }

        if(this._expressao_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._string_ == oldChild)
        {
            setString((PString) newChild);
            return;
        }

        for(ListIterator<PExpressao> i = this._expressao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpressao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
