/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import java.util.*;
import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ARefParametroFormal extends PParametroFormal
{
    private final LinkedList<PRefFormal> _refFormal_ = new LinkedList<PRefFormal>();

    public ARefParametroFormal()
    {
        // Constructor
    }

    public ARefParametroFormal(
        @SuppressWarnings("hiding") List<?> _refFormal_)
    {
        // Constructor
        setRefFormal(_refFormal_);

    }

    @Override
    public Object clone()
    {
        return new ARefParametroFormal(
            cloneList(this._refFormal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARefParametroFormal(this);
    }

    public LinkedList<PRefFormal> getRefFormal()
    {
        return this._refFormal_;
    }

    public void setRefFormal(List<?> list)
    {
        for(PRefFormal e : this._refFormal_)
        {
            e.parent(null);
        }
        this._refFormal_.clear();

        for(Object obj_e : list)
        {
            PRefFormal e = (PRefFormal) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._refFormal_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._refFormal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._refFormal_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PRefFormal> i = this._refFormal_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRefFormal) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
