/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ASentencaProcedure extends PSentencaProcedure
{
    private TProcedure _procedure_;
    private TIdentificador _identificador_;
    private PParametrosReais _parametrosReais_;

    public ASentencaProcedure()
    {
        // Constructor
    }

    public ASentencaProcedure(
        @SuppressWarnings("hiding") TProcedure _procedure_,
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") PParametrosReais _parametrosReais_)
    {
        // Constructor
        setProcedure(_procedure_);

        setIdentificador(_identificador_);

        setParametrosReais(_parametrosReais_);

    }

    @Override
    public Object clone()
    {
        return new ASentencaProcedure(
            cloneNode(this._procedure_),
            cloneNode(this._identificador_),
            cloneNode(this._parametrosReais_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASentencaProcedure(this);
    }

    public TProcedure getProcedure()
    {
        return this._procedure_;
    }

    public void setProcedure(TProcedure node)
    {
        if(this._procedure_ != null)
        {
            this._procedure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._procedure_ = node;
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public PParametrosReais getParametrosReais()
    {
        return this._parametrosReais_;
    }

    public void setParametrosReais(PParametrosReais node)
    {
        if(this._parametrosReais_ != null)
        {
            this._parametrosReais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametrosReais_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._procedure_)
            + toString(this._identificador_)
            + toString(this._parametrosReais_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._procedure_ == child)
        {
            this._procedure_ = null;
            return;
        }

        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._parametrosReais_ == child)
        {
            this._parametrosReais_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._procedure_ == oldChild)
        {
            setProcedure((TProcedure) newChild);
            return;
        }

        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._parametrosReais_ == oldChild)
        {
            setParametrosReais((PParametrosReais) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
