/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesDefinicaoSentencaFechada extends PDefinicaoSentencaFechada
{
    private PDefinicaoSentencaSimples _definicaoSentencaSimples_;

    public ASimplesDefinicaoSentencaFechada()
    {
        // Constructor
    }

    public ASimplesDefinicaoSentencaFechada(
        @SuppressWarnings("hiding") PDefinicaoSentencaSimples _definicaoSentencaSimples_)
    {
        // Constructor
        setDefinicaoSentencaSimples(_definicaoSentencaSimples_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesDefinicaoSentencaFechada(
            cloneNode(this._definicaoSentencaSimples_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesDefinicaoSentencaFechada(this);
    }

    public PDefinicaoSentencaSimples getDefinicaoSentencaSimples()
    {
        return this._definicaoSentencaSimples_;
    }

    public void setDefinicaoSentencaSimples(PDefinicaoSentencaSimples node)
    {
        if(this._definicaoSentencaSimples_ != null)
        {
            this._definicaoSentencaSimples_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoSentencaSimples_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definicaoSentencaSimples_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definicaoSentencaSimples_ == child)
        {
            this._definicaoSentencaSimples_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definicaoSentencaSimples_ == oldChild)
        {
            setDefinicaoSentencaSimples((PDefinicaoSentencaSimples) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
