/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class ASubrangeTipoIdOuOrdinal extends PTipoIdOuOrdinal
{
    private PTipoSubrange _tipoSubrange_;

    public ASubrangeTipoIdOuOrdinal()
    {
        // Constructor
    }

    public ASubrangeTipoIdOuOrdinal(
        @SuppressWarnings("hiding") PTipoSubrange _tipoSubrange_)
    {
        // Constructor
        setTipoSubrange(_tipoSubrange_);

    }

    @Override
    public Object clone()
    {
        return new ASubrangeTipoIdOuOrdinal(
            cloneNode(this._tipoSubrange_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubrangeTipoIdOuOrdinal(this);
    }

    public PTipoSubrange getTipoSubrange()
    {
        return this._tipoSubrange_;
    }

    public void setTipoSubrange(PTipoSubrange node)
    {
        if(this._tipoSubrange_ != null)
        {
            this._tipoSubrange_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoSubrange_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoSubrange_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoSubrange_ == child)
        {
            this._tipoSubrange_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoSubrange_ == oldChild)
        {
            setTipoSubrange((PTipoSubrange) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
