/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.node;

import br.com.ufs.pascalito.analysis.*;

@SuppressWarnings("nls")
public final class AUnicoDefinicaoTipos extends PDefinicaoTipos
{
    private PDefinicaoTipo _definicaoTipo_;

    public AUnicoDefinicaoTipos()
    {
        // Constructor
    }

    public AUnicoDefinicaoTipos(
        @SuppressWarnings("hiding") PDefinicaoTipo _definicaoTipo_)
    {
        // Constructor
        setDefinicaoTipo(_definicaoTipo_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoDefinicaoTipos(
            cloneNode(this._definicaoTipo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoDefinicaoTipos(this);
    }

    public PDefinicaoTipo getDefinicaoTipo()
    {
        return this._definicaoTipo_;
    }

    public void setDefinicaoTipo(PDefinicaoTipo node)
    {
        if(this._definicaoTipo_ != null)
        {
            this._definicaoTipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoTipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definicaoTipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definicaoTipo_ == child)
        {
            this._definicaoTipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definicaoTipo_ == oldChild)
        {
            setDefinicaoTipo((PDefinicaoTipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
