/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.com.ufs.pascalito.analysis;

import java.util.*;
import br.com.ufs.pascalito.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgram().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getCabecalhoPrograma() != null)
        {
            node.getCabecalhoPrograma().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAProgram(node);
    }

    public void inAUnicoCabecalhoPrograma(AUnicoCabecalhoPrograma node)
    {
        defaultIn(node);
    }

    public void outAUnicoCabecalhoPrograma(AUnicoCabecalhoPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoCabecalhoPrograma(AUnicoCabecalhoPrograma node)
    {
        inAUnicoCabecalhoPrograma(node);
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAUnicoCabecalhoPrograma(node);
    }

    public void inAMultiploCabecalhoPrograma(AMultiploCabecalhoPrograma node)
    {
        defaultIn(node);
    }

    public void outAMultiploCabecalhoPrograma(AMultiploCabecalhoPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploCabecalhoPrograma(AMultiploCabecalhoPrograma node)
    {
        inAMultiploCabecalhoPrograma(node);
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getAbreParenteses() != null)
        {
            node.getAbreParenteses().apply(this);
        }
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getFechaParenteses() != null)
        {
            node.getFechaParenteses().apply(this);
        }
        outAMultiploCabecalhoPrograma(node);
    }

    public void inABloco(ABloco node)
    {
        defaultIn(node);
    }

    public void outABloco(ABloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        inABloco(node);
        if(node.getDeclaracaoLabels() != null)
        {
            node.getDeclaracaoLabels().apply(this);
        }
        if(node.getDeclaracaoTipos() != null)
        {
            node.getDeclaracaoTipos().apply(this);
        }
        if(node.getDeclaracoesVariaveis() != null)
        {
            node.getDeclaracoesVariaveis().apply(this);
        }
        if(node.getDeclaracoesProcFuncoes() != null)
        {
            node.getDeclaracoesProcFuncoes().apply(this);
        }
        if(node.getSentencaComposta() != null)
        {
            node.getSentencaComposta().apply(this);
        }
        outABloco(node);
    }

    public void inAUnicoIdentificadores(AUnicoIdentificadores node)
    {
        defaultIn(node);
    }

    public void outAUnicoIdentificadores(AUnicoIdentificadores node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoIdentificadores(AUnicoIdentificadores node)
    {
        inAUnicoIdentificadores(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAUnicoIdentificadores(node);
    }

    public void inAMultiploIdentificadores(AMultiploIdentificadores node)
    {
        defaultIn(node);
    }

    public void outAMultiploIdentificadores(AMultiploIdentificadores node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploIdentificadores(AMultiploIdentificadores node)
    {
        inAMultiploIdentificadores(node);
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAMultiploIdentificadores(node);
    }

    public void inAIntegerIdentificadorTipoOrdinal(AIntegerIdentificadorTipoOrdinal node)
    {
        defaultIn(node);
    }

    public void outAIntegerIdentificadorTipoOrdinal(AIntegerIdentificadorTipoOrdinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntegerIdentificadorTipoOrdinal(AIntegerIdentificadorTipoOrdinal node)
    {
        inAIntegerIdentificadorTipoOrdinal(node);
        if(node.getInteger() != null)
        {
            node.getInteger().apply(this);
        }
        outAIntegerIdentificadorTipoOrdinal(node);
    }

    public void inAStringIdentificadorTipoOrdinal(AStringIdentificadorTipoOrdinal node)
    {
        defaultIn(node);
    }

    public void outAStringIdentificadorTipoOrdinal(AStringIdentificadorTipoOrdinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringIdentificadorTipoOrdinal(AStringIdentificadorTipoOrdinal node)
    {
        inAStringIdentificadorTipoOrdinal(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringIdentificadorTipoOrdinal(node);
    }

    public void inABooleanIdentificadorTipoOrdinal(ABooleanIdentificadorTipoOrdinal node)
    {
        defaultIn(node);
    }

    public void outABooleanIdentificadorTipoOrdinal(ABooleanIdentificadorTipoOrdinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanIdentificadorTipoOrdinal(ABooleanIdentificadorTipoOrdinal node)
    {
        inABooleanIdentificadorTipoOrdinal(node);
        if(node.getBoolean() != null)
        {
            node.getBoolean().apply(this);
        }
        outABooleanIdentificadorTipoOrdinal(node);
    }

    public void inAIdentificadorIdentificadorTipo(AIdentificadorIdentificadorTipo node)
    {
        defaultIn(node);
    }

    public void outAIdentificadorIdentificadorTipo(AIdentificadorIdentificadorTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificadorIdentificadorTipo(AIdentificadorIdentificadorTipo node)
    {
        inAIdentificadorIdentificadorTipo(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAIdentificadorIdentificadorTipo(node);
    }

    public void inAOrdinalIdentificadorTipo(AOrdinalIdentificadorTipo node)
    {
        defaultIn(node);
    }

    public void outAOrdinalIdentificadorTipo(AOrdinalIdentificadorTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrdinalIdentificadorTipo(AOrdinalIdentificadorTipo node)
    {
        inAOrdinalIdentificadorTipo(node);
        if(node.getIdentificadorTipoOrdinal() != null)
        {
            node.getIdentificadorTipoOrdinal().apply(this);
        }
        outAOrdinalIdentificadorTipo(node);
    }

    public void inADeclaracaoLabels(ADeclaracaoLabels node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoLabels(ADeclaracaoLabels node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoLabels(ADeclaracaoLabels node)
    {
        inADeclaracaoLabels(node);
        if(node.getLabel() != null)
        {
            node.getLabel().apply(this);
        }
        if(node.getLabels() != null)
        {
            node.getLabels().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        outADeclaracaoLabels(node);
    }

    public void inAEmptyDeclaracaoLabels(AEmptyDeclaracaoLabels node)
    {
        defaultIn(node);
    }

    public void outAEmptyDeclaracaoLabels(AEmptyDeclaracaoLabels node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyDeclaracaoLabels(AEmptyDeclaracaoLabels node)
    {
        inAEmptyDeclaracaoLabels(node);
        outAEmptyDeclaracaoLabels(node);
    }

    public void inAUnicoLabels(AUnicoLabels node)
    {
        defaultIn(node);
    }

    public void outAUnicoLabels(AUnicoLabels node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoLabels(AUnicoLabels node)
    {
        inAUnicoLabels(node);
        if(node.getLabel() != null)
        {
            node.getLabel().apply(this);
        }
        outAUnicoLabels(node);
    }

    public void inAMultiploLabels(AMultiploLabels node)
    {
        defaultIn(node);
    }

    public void outAMultiploLabels(AMultiploLabels node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploLabels(AMultiploLabels node)
    {
        inAMultiploLabels(node);
        if(node.getLabels() != null)
        {
            node.getLabels().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getLabel() != null)
        {
            node.getLabel().apply(this);
        }
        outAMultiploLabels(node);
    }

    public void inALabel(ALabel node)
    {
        defaultIn(node);
    }

    public void outALabel(ALabel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALabel(ALabel node)
    {
        inALabel(node);
        if(node.getConstInteiro() != null)
        {
            node.getConstInteiro().apply(this);
        }
        outALabel(node);
    }

    public void inAConstNumeroSemSinal(AConstNumeroSemSinal node)
    {
        defaultIn(node);
    }

    public void outAConstNumeroSemSinal(AConstNumeroSemSinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstNumeroSemSinal(AConstNumeroSemSinal node)
    {
        inAConstNumeroSemSinal(node);
        if(node.getConstInteiro() != null)
        {
            node.getConstInteiro().apply(this);
        }
        outAConstNumeroSemSinal(node);
    }

    public void inADeclaracaoTipos(ADeclaracaoTipos node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoTipos(ADeclaracaoTipos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoTipos(ADeclaracaoTipos node)
    {
        inADeclaracaoTipos(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getDefinicaoTipos() != null)
        {
            node.getDefinicaoTipos().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        outADeclaracaoTipos(node);
    }

    public void inAEmptyDeclaracaoTipos(AEmptyDeclaracaoTipos node)
    {
        defaultIn(node);
    }

    public void outAEmptyDeclaracaoTipos(AEmptyDeclaracaoTipos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyDeclaracaoTipos(AEmptyDeclaracaoTipos node)
    {
        inAEmptyDeclaracaoTipos(node);
        outAEmptyDeclaracaoTipos(node);
    }

    public void inAUnicoDefinicaoTipos(AUnicoDefinicaoTipos node)
    {
        defaultIn(node);
    }

    public void outAUnicoDefinicaoTipos(AUnicoDefinicaoTipos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoDefinicaoTipos(AUnicoDefinicaoTipos node)
    {
        inAUnicoDefinicaoTipos(node);
        if(node.getDefinicaoTipo() != null)
        {
            node.getDefinicaoTipo().apply(this);
        }
        outAUnicoDefinicaoTipos(node);
    }

    public void inAMultiploDefinicaoTipos(AMultiploDefinicaoTipos node)
    {
        defaultIn(node);
    }

    public void outAMultiploDefinicaoTipos(AMultiploDefinicaoTipos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploDefinicaoTipos(AMultiploDefinicaoTipos node)
    {
        inAMultiploDefinicaoTipos(node);
        if(node.getDefinicaoTipos() != null)
        {
            node.getDefinicaoTipos().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getDefinicaoTipo() != null)
        {
            node.getDefinicaoTipo().apply(this);
        }
        outAMultiploDefinicaoTipos(node);
    }

    public void inADefinicaoTipo(ADefinicaoTipo node)
    {
        defaultIn(node);
    }

    public void outADefinicaoTipo(ADefinicaoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefinicaoTipo(ADefinicaoTipo node)
    {
        inADefinicaoTipo(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        if(node.getDenotadorTipo() != null)
        {
            node.getDenotadorTipo().apply(this);
        }
        outADefinicaoTipo(node);
    }

    public void inAExistenteDenotadorTipo(AExistenteDenotadorTipo node)
    {
        defaultIn(node);
    }

    public void outAExistenteDenotadorTipo(AExistenteDenotadorTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExistenteDenotadorTipo(AExistenteDenotadorTipo node)
    {
        inAExistenteDenotadorTipo(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAExistenteDenotadorTipo(node);
    }

    public void inANovoDenotadorTipo(ANovoDenotadorTipo node)
    {
        defaultIn(node);
    }

    public void outANovoDenotadorTipo(ANovoDenotadorTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANovoDenotadorTipo(ANovoDenotadorTipo node)
    {
        inANovoDenotadorTipo(node);
        if(node.getNovoTipo() != null)
        {
            node.getNovoTipo().apply(this);
        }
        outANovoDenotadorTipo(node);
    }

    public void inAOrdinalDenotadorTipo(AOrdinalDenotadorTipo node)
    {
        defaultIn(node);
    }

    public void outAOrdinalDenotadorTipo(AOrdinalDenotadorTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrdinalDenotadorTipo(AOrdinalDenotadorTipo node)
    {
        inAOrdinalDenotadorTipo(node);
        if(node.getIdentificadorTipoOrdinal() != null)
        {
            node.getIdentificadorTipoOrdinal().apply(this);
        }
        outAOrdinalDenotadorTipo(node);
    }

    public void inAOrdinalNovoTipo(AOrdinalNovoTipo node)
    {
        defaultIn(node);
    }

    public void outAOrdinalNovoTipo(AOrdinalNovoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrdinalNovoTipo(AOrdinalNovoTipo node)
    {
        inAOrdinalNovoTipo(node);
        if(node.getNovoTipoOrdinal() != null)
        {
            node.getNovoTipoOrdinal().apply(this);
        }
        outAOrdinalNovoTipo(node);
    }

    public void inAArrayNovoTipo(AArrayNovoTipo node)
    {
        defaultIn(node);
    }

    public void outAArrayNovoTipo(AArrayNovoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayNovoTipo(AArrayNovoTipo node)
    {
        inAArrayNovoTipo(node);
        if(node.getTipoArray() != null)
        {
            node.getTipoArray().apply(this);
        }
        outAArrayNovoTipo(node);
    }

    public void inATipoArray(ATipoArray node)
    {
        defaultIn(node);
    }

    public void outATipoArray(ATipoArray node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoArray(ATipoArray node)
    {
        inATipoArray(node);
        if(node.getArray() != null)
        {
            node.getArray().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getTiposOrdinais() != null)
        {
            node.getTiposOrdinais().apply(this);
        }
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        if(node.getOf() != null)
        {
            node.getOf().apply(this);
        }
        if(node.getDenotadorTipo() != null)
        {
            node.getDenotadorTipo().apply(this);
        }
        outATipoArray(node);
    }

    public void inAUnicoTiposOrdinais(AUnicoTiposOrdinais node)
    {
        defaultIn(node);
    }

    public void outAUnicoTiposOrdinais(AUnicoTiposOrdinais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoTiposOrdinais(AUnicoTiposOrdinais node)
    {
        inAUnicoTiposOrdinais(node);
        if(node.getTipoOrdinal() != null)
        {
            node.getTipoOrdinal().apply(this);
        }
        outAUnicoTiposOrdinais(node);
    }

    public void inAMultiploTiposOrdinais(AMultiploTiposOrdinais node)
    {
        defaultIn(node);
    }

    public void outAMultiploTiposOrdinais(AMultiploTiposOrdinais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploTiposOrdinais(AMultiploTiposOrdinais node)
    {
        inAMultiploTiposOrdinais(node);
        if(node.getTiposOrdinais() != null)
        {
            node.getTiposOrdinais().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getTipoOrdinal() != null)
        {
            node.getTipoOrdinal().apply(this);
        }
        outAMultiploTiposOrdinais(node);
    }

    public void inANovoTipoOrdinal(ANovoTipoOrdinal node)
    {
        defaultIn(node);
    }

    public void outANovoTipoOrdinal(ANovoTipoOrdinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANovoTipoOrdinal(ANovoTipoOrdinal node)
    {
        inANovoTipoOrdinal(node);
        if(node.getNovoTipoOrdinal() != null)
        {
            node.getNovoTipoOrdinal().apply(this);
        }
        outANovoTipoOrdinal(node);
    }

    public void inAExistenteTipoOrdinal(AExistenteTipoOrdinal node)
    {
        defaultIn(node);
    }

    public void outAExistenteTipoOrdinal(AExistenteTipoOrdinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExistenteTipoOrdinal(AExistenteTipoOrdinal node)
    {
        inAExistenteTipoOrdinal(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAExistenteTipoOrdinal(node);
    }

    public void inAEnumeradoNovoTipoOrdinal(AEnumeradoNovoTipoOrdinal node)
    {
        defaultIn(node);
    }

    public void outAEnumeradoNovoTipoOrdinal(AEnumeradoNovoTipoOrdinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEnumeradoNovoTipoOrdinal(AEnumeradoNovoTipoOrdinal node)
    {
        inAEnumeradoNovoTipoOrdinal(node);
        if(node.getTipoEnumerado() != null)
        {
            node.getTipoEnumerado().apply(this);
        }
        outAEnumeradoNovoTipoOrdinal(node);
    }

    public void inASubrangeNovoTipoOrdinal(ASubrangeNovoTipoOrdinal node)
    {
        defaultIn(node);
    }

    public void outASubrangeNovoTipoOrdinal(ASubrangeNovoTipoOrdinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubrangeNovoTipoOrdinal(ASubrangeNovoTipoOrdinal node)
    {
        inASubrangeNovoTipoOrdinal(node);
        if(node.getTipoSubrange() != null)
        {
            node.getTipoSubrange().apply(this);
        }
        outASubrangeNovoTipoOrdinal(node);
    }

    public void inATipoEnumerado(ATipoEnumerado node)
    {
        defaultIn(node);
    }

    public void outATipoEnumerado(ATipoEnumerado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoEnumerado(ATipoEnumerado node)
    {
        inATipoEnumerado(node);
        if(node.getAbreParenteses() != null)
        {
            node.getAbreParenteses().apply(this);
        }
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getFechaParenteses() != null)
        {
            node.getFechaParenteses().apply(this);
        }
        outATipoEnumerado(node);
    }

    public void inATipoSubrange(ATipoSubrange node)
    {
        defaultIn(node);
    }

    public void outATipoSubrange(ATipoSubrange node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoSubrange(ATipoSubrange node)
    {
        inATipoSubrange(node);
        if(node.getInicio() != null)
        {
            node.getInicio().apply(this);
        }
        if(node.getPontoPonto() != null)
        {
            node.getPontoPonto().apply(this);
        }
        if(node.getFim() != null)
        {
            node.getFim().apply(this);
        }
        outATipoSubrange(node);
    }

    public void inANumeroConstante(ANumeroConstante node)
    {
        defaultIn(node);
    }

    public void outANumeroConstante(ANumeroConstante node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroConstante(ANumeroConstante node)
    {
        inANumeroConstante(node);
        if(node.getSinal() != null)
        {
            node.getSinal().apply(this);
        }
        if(node.getConstNumeroSemSinal() != null)
        {
            node.getConstNumeroSemSinal().apply(this);
        }
        outANumeroConstante(node);
    }

    public void inAStringConstante(AStringConstante node)
    {
        defaultIn(node);
    }

    public void outAStringConstante(AStringConstante node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringConstante(AStringConstante node)
    {
        inAStringConstante(node);
        if(node.getConstString() != null)
        {
            node.getConstString().apply(this);
        }
        outAStringConstante(node);
    }

    public void inANumeroConstanteSemSinal(ANumeroConstanteSemSinal node)
    {
        defaultIn(node);
    }

    public void outANumeroConstanteSemSinal(ANumeroConstanteSemSinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroConstanteSemSinal(ANumeroConstanteSemSinal node)
    {
        inANumeroConstanteSemSinal(node);
        if(node.getConstNumeroSemSinal() != null)
        {
            node.getConstNumeroSemSinal().apply(this);
        }
        outANumeroConstanteSemSinal(node);
    }

    public void inAStringConstanteSemSinal(AStringConstanteSemSinal node)
    {
        defaultIn(node);
    }

    public void outAStringConstanteSemSinal(AStringConstanteSemSinal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringConstanteSemSinal(AStringConstanteSemSinal node)
    {
        inAStringConstanteSemSinal(node);
        if(node.getConstString() != null)
        {
            node.getConstString().apply(this);
        }
        outAStringConstanteSemSinal(node);
    }

    public void inADeclaracoesVariaveis(ADeclaracoesVariaveis node)
    {
        defaultIn(node);
    }

    public void outADeclaracoesVariaveis(ADeclaracoesVariaveis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracoesVariaveis(ADeclaracoesVariaveis node)
    {
        inADeclaracoesVariaveis(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getDeclaracaoVariaveis() != null)
        {
            node.getDeclaracaoVariaveis().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        outADeclaracoesVariaveis(node);
    }

    public void inAEmptyDeclaracoesVariaveis(AEmptyDeclaracoesVariaveis node)
    {
        defaultIn(node);
    }

    public void outAEmptyDeclaracoesVariaveis(AEmptyDeclaracoesVariaveis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyDeclaracoesVariaveis(AEmptyDeclaracoesVariaveis node)
    {
        inAEmptyDeclaracoesVariaveis(node);
        outAEmptyDeclaracoesVariaveis(node);
    }

    public void inAUnicoDeclaracaoVariaveis(AUnicoDeclaracaoVariaveis node)
    {
        defaultIn(node);
    }

    public void outAUnicoDeclaracaoVariaveis(AUnicoDeclaracaoVariaveis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoDeclaracaoVariaveis(AUnicoDeclaracaoVariaveis node)
    {
        inAUnicoDeclaracaoVariaveis(node);
        if(node.getDeclaracaoVariavel() != null)
        {
            node.getDeclaracaoVariavel().apply(this);
        }
        outAUnicoDeclaracaoVariaveis(node);
    }

    public void inAMultiploDeclaracaoVariaveis(AMultiploDeclaracaoVariaveis node)
    {
        defaultIn(node);
    }

    public void outAMultiploDeclaracaoVariaveis(AMultiploDeclaracaoVariaveis node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploDeclaracaoVariaveis(AMultiploDeclaracaoVariaveis node)
    {
        inAMultiploDeclaracaoVariaveis(node);
        if(node.getDeclaracaoVariaveis() != null)
        {
            node.getDeclaracaoVariaveis().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getDeclaracaoVariavel() != null)
        {
            node.getDeclaracaoVariavel().apply(this);
        }
        outAMultiploDeclaracaoVariaveis(node);
    }

    public void inADeclaracaoVariavel(ADeclaracaoVariavel node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoVariavel(ADeclaracaoVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoVariavel(ADeclaracaoVariavel node)
    {
        inADeclaracaoVariavel(node);
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getDenotadorTipo() != null)
        {
            node.getDenotadorTipo().apply(this);
        }
        outADeclaracaoVariavel(node);
    }

    public void inADeclaracoesProcFuncoes(ADeclaracoesProcFuncoes node)
    {
        defaultIn(node);
    }

    public void outADeclaracoesProcFuncoes(ADeclaracoesProcFuncoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracoesProcFuncoes(ADeclaracoesProcFuncoes node)
    {
        inADeclaracoesProcFuncoes(node);
        if(node.getDeclaracaoProcFuncoes() != null)
        {
            node.getDeclaracaoProcFuncoes().apply(this);
        }
        outADeclaracoesProcFuncoes(node);
    }

    public void inAEmptyDeclaracoesProcFuncoes(AEmptyDeclaracoesProcFuncoes node)
    {
        defaultIn(node);
    }

    public void outAEmptyDeclaracoesProcFuncoes(AEmptyDeclaracoesProcFuncoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyDeclaracoesProcFuncoes(AEmptyDeclaracoesProcFuncoes node)
    {
        inAEmptyDeclaracoesProcFuncoes(node);
        outAEmptyDeclaracoesProcFuncoes(node);
    }

    public void inAUnicoDeclaracaoProcFuncoes(AUnicoDeclaracaoProcFuncoes node)
    {
        defaultIn(node);
    }

    public void outAUnicoDeclaracaoProcFuncoes(AUnicoDeclaracaoProcFuncoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoDeclaracaoProcFuncoes(AUnicoDeclaracaoProcFuncoes node)
    {
        inAUnicoDeclaracaoProcFuncoes(node);
        if(node.getDeclaracaoProcFuncao() != null)
        {
            node.getDeclaracaoProcFuncao().apply(this);
        }
        outAUnicoDeclaracaoProcFuncoes(node);
    }

    public void inAMultiploDeclaracaoProcFuncoes(AMultiploDeclaracaoProcFuncoes node)
    {
        defaultIn(node);
    }

    public void outAMultiploDeclaracaoProcFuncoes(AMultiploDeclaracaoProcFuncoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploDeclaracaoProcFuncoes(AMultiploDeclaracaoProcFuncoes node)
    {
        inAMultiploDeclaracaoProcFuncoes(node);
        if(node.getDeclaracaoProcFuncoes() != null)
        {
            node.getDeclaracaoProcFuncoes().apply(this);
        }
        if(node.getDeclaracaoProcFuncao() != null)
        {
            node.getDeclaracaoProcFuncao().apply(this);
        }
        outAMultiploDeclaracaoProcFuncoes(node);
    }

    public void inAProcedureDeclaracaoProcFuncao(AProcedureDeclaracaoProcFuncao node)
    {
        defaultIn(node);
    }

    public void outAProcedureDeclaracaoProcFuncao(AProcedureDeclaracaoProcFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedureDeclaracaoProcFuncao(AProcedureDeclaracaoProcFuncao node)
    {
        inAProcedureDeclaracaoProcFuncao(node);
        if(node.getDeclaracaoProcedure() != null)
        {
            node.getDeclaracaoProcedure().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        outAProcedureDeclaracaoProcFuncao(node);
    }

    public void inAFuncaoDeclaracaoProcFuncao(AFuncaoDeclaracaoProcFuncao node)
    {
        defaultIn(node);
    }

    public void outAFuncaoDeclaracaoProcFuncao(AFuncaoDeclaracaoProcFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoDeclaracaoProcFuncao(AFuncaoDeclaracaoProcFuncao node)
    {
        inAFuncaoDeclaracaoProcFuncao(node);
        if(node.getDeclaracaoFuncao() != null)
        {
            node.getDeclaracaoFuncao().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        outAFuncaoDeclaracaoProcFuncao(node);
    }

    public void inADeclaracaoProcedure(ADeclaracaoProcedure node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoProcedure(ADeclaracaoProcedure node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoProcedure(ADeclaracaoProcedure node)
    {
        inADeclaracaoProcedure(node);
        if(node.getCabecalhoProcedure() != null)
        {
            node.getCabecalhoProcedure().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outADeclaracaoProcedure(node);
    }

    public void inADeclaracaoFuncao(ADeclaracaoFuncao node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoFuncao(ADeclaracaoFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoFuncao(ADeclaracaoFuncao node)
    {
        inADeclaracaoFuncao(node);
        if(node.getCabecalhoFuncao() != null)
        {
            node.getCabecalhoFuncao().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outADeclaracaoFuncao(node);
    }

    public void inACabecalhoProcedure(ACabecalhoProcedure node)
    {
        defaultIn(node);
    }

    public void outACabecalhoProcedure(ACabecalhoProcedure node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACabecalhoProcedure(ACabecalhoProcedure node)
    {
        inACabecalhoProcedure(node);
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getParametrosFormais() != null)
        {
            node.getParametrosFormais().apply(this);
        }
        outACabecalhoProcedure(node);
    }

    public void inACabecalhoFuncao(ACabecalhoFuncao node)
    {
        defaultIn(node);
    }

    public void outACabecalhoFuncao(ACabecalhoFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACabecalhoFuncao(ACabecalhoFuncao node)
    {
        inACabecalhoFuncao(node);
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getParametrosFormais() != null)
        {
            node.getParametrosFormais().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getTipoResultado() != null)
        {
            node.getTipoResultado().apply(this);
        }
        outACabecalhoFuncao(node);
    }

    public void inAParametrosFormais(AParametrosFormais node)
    {
        defaultIn(node);
    }

    public void outAParametrosFormais(AParametrosFormais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametrosFormais(AParametrosFormais node)
    {
        inAParametrosFormais(node);
        if(node.getAbreParenteses() != null)
        {
            node.getAbreParenteses().apply(this);
        }
        if(node.getSecaoParametrosFormais() != null)
        {
            node.getSecaoParametrosFormais().apply(this);
        }
        if(node.getFechaParenteses() != null)
        {
            node.getFechaParenteses().apply(this);
        }
        outAParametrosFormais(node);
    }

    public void inAEmptyParametrosFormais(AEmptyParametrosFormais node)
    {
        defaultIn(node);
    }

    public void outAEmptyParametrosFormais(AEmptyParametrosFormais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyParametrosFormais(AEmptyParametrosFormais node)
    {
        inAEmptyParametrosFormais(node);
        outAEmptyParametrosFormais(node);
    }

    public void inAUnicoSecaoParametrosFormais(AUnicoSecaoParametrosFormais node)
    {
        defaultIn(node);
    }

    public void outAUnicoSecaoParametrosFormais(AUnicoSecaoParametrosFormais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoSecaoParametrosFormais(AUnicoSecaoParametrosFormais node)
    {
        inAUnicoSecaoParametrosFormais(node);
        if(node.getSecaoParametroFormal() != null)
        {
            node.getSecaoParametroFormal().apply(this);
        }
        outAUnicoSecaoParametrosFormais(node);
    }

    public void inAMultiploSecaoParametrosFormais(AMultiploSecaoParametrosFormais node)
    {
        defaultIn(node);
    }

    public void outAMultiploSecaoParametrosFormais(AMultiploSecaoParametrosFormais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploSecaoParametrosFormais(AMultiploSecaoParametrosFormais node)
    {
        inAMultiploSecaoParametrosFormais(node);
        if(node.getSecaoParametrosFormais() != null)
        {
            node.getSecaoParametrosFormais().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getSecaoParametroFormal() != null)
        {
            node.getSecaoParametroFormal().apply(this);
        }
        outAMultiploSecaoParametrosFormais(node);
    }

    public void inAValorSecaoParametroFormal(AValorSecaoParametroFormal node)
    {
        defaultIn(node);
    }

    public void outAValorSecaoParametroFormal(AValorSecaoParametroFormal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValorSecaoParametroFormal(AValorSecaoParametroFormal node)
    {
        inAValorSecaoParametroFormal(node);
        if(node.getSpecParamValor() != null)
        {
            node.getSpecParamValor().apply(this);
        }
        outAValorSecaoParametroFormal(node);
    }

    public void inAVariavelSecaoParametroFormal(AVariavelSecaoParametroFormal node)
    {
        defaultIn(node);
    }

    public void outAVariavelSecaoParametroFormal(AVariavelSecaoParametroFormal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelSecaoParametroFormal(AVariavelSecaoParametroFormal node)
    {
        inAVariavelSecaoParametroFormal(node);
        if(node.getSpecParamVariavel() != null)
        {
            node.getSpecParamVariavel().apply(this);
        }
        outAVariavelSecaoParametroFormal(node);
    }

    public void inAArraySecaoParametroFormal(AArraySecaoParametroFormal node)
    {
        defaultIn(node);
    }

    public void outAArraySecaoParametroFormal(AArraySecaoParametroFormal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArraySecaoParametroFormal(AArraySecaoParametroFormal node)
    {
        inAArraySecaoParametroFormal(node);
        if(node.getSpecParamArray() != null)
        {
            node.getSpecParamArray().apply(this);
        }
        outAArraySecaoParametroFormal(node);
    }

    public void inASpecParamValor(ASpecParamValor node)
    {
        defaultIn(node);
    }

    public void outASpecParamValor(ASpecParamValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASpecParamValor(ASpecParamValor node)
    {
        inASpecParamValor(node);
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getIdentificadorTipo() != null)
        {
            node.getIdentificadorTipo().apply(this);
        }
        outASpecParamValor(node);
    }

    public void inASpecParamVariavel(ASpecParamVariavel node)
    {
        defaultIn(node);
    }

    public void outASpecParamVariavel(ASpecParamVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASpecParamVariavel(ASpecParamVariavel node)
    {
        inASpecParamVariavel(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getIdentificadorTipo() != null)
        {
            node.getIdentificadorTipo().apply(this);
        }
        outASpecParamVariavel(node);
    }

    public void inAValorSpecParamArray(AValorSpecParamArray node)
    {
        defaultIn(node);
    }

    public void outAValorSpecParamArray(AValorSpecParamArray node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValorSpecParamArray(AValorSpecParamArray node)
    {
        inAValorSpecParamArray(node);
        if(node.getSpecParamArrayValor() != null)
        {
            node.getSpecParamArrayValor().apply(this);
        }
        outAValorSpecParamArray(node);
    }

    public void inAVariavelSpecParamArray(AVariavelSpecParamArray node)
    {
        defaultIn(node);
    }

    public void outAVariavelSpecParamArray(AVariavelSpecParamArray node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelSpecParamArray(AVariavelSpecParamArray node)
    {
        inAVariavelSpecParamArray(node);
        if(node.getSpecParamArrayVariavel() != null)
        {
            node.getSpecParamArrayVariavel().apply(this);
        }
        outAVariavelSpecParamArray(node);
    }

    public void inASpecParamArrayValor(ASpecParamArrayValor node)
    {
        defaultIn(node);
    }

    public void outASpecParamArrayValor(ASpecParamArrayValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASpecParamArrayValor(ASpecParamArrayValor node)
    {
        inASpecParamArrayValor(node);
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getSchemaArray() != null)
        {
            node.getSchemaArray().apply(this);
        }
        outASpecParamArrayValor(node);
    }

    public void inASpecParamArrayVariavel(ASpecParamArrayVariavel node)
    {
        defaultIn(node);
    }

    public void outASpecParamArrayVariavel(ASpecParamArrayVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASpecParamArrayVariavel(ASpecParamArrayVariavel node)
    {
        inASpecParamArrayVariavel(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getIdentificadores() != null)
        {
            node.getIdentificadores().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getSchemaArray() != null)
        {
            node.getSchemaArray().apply(this);
        }
        outASpecParamArrayVariavel(node);
    }

    public void inASchemaArray(ASchemaArray node)
    {
        defaultIn(node);
    }

    public void outASchemaArray(ASchemaArray node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASchemaArray(ASchemaArray node)
    {
        inASchemaArray(node);
        if(node.getArray() != null)
        {
            node.getArray().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getSpecTiposIndices() != null)
        {
            node.getSpecTiposIndices().apply(this);
        }
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        if(node.getOf() != null)
        {
            node.getOf().apply(this);
        }
        if(node.getAbreParenteses() != null)
        {
            node.getAbreParenteses().apply(this);
        }
        if(node.getIdentificadorSchemaArray() != null)
        {
            node.getIdentificadorSchemaArray().apply(this);
        }
        if(node.getFechaParenteses() != null)
        {
            node.getFechaParenteses().apply(this);
        }
        outASchemaArray(node);
    }

    public void inAUnicoSpecTiposIndices(AUnicoSpecTiposIndices node)
    {
        defaultIn(node);
    }

    public void outAUnicoSpecTiposIndices(AUnicoSpecTiposIndices node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoSpecTiposIndices(AUnicoSpecTiposIndices node)
    {
        inAUnicoSpecTiposIndices(node);
        if(node.getSpecTipoIndice() != null)
        {
            node.getSpecTipoIndice().apply(this);
        }
        outAUnicoSpecTiposIndices(node);
    }

    public void inAMultiploSpecTiposIndices(AMultiploSpecTiposIndices node)
    {
        defaultIn(node);
    }

    public void outAMultiploSpecTiposIndices(AMultiploSpecTiposIndices node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploSpecTiposIndices(AMultiploSpecTiposIndices node)
    {
        inAMultiploSpecTiposIndices(node);
        if(node.getSpecTiposIndices() != null)
        {
            node.getSpecTiposIndices().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getSpecTipoIndice() != null)
        {
            node.getSpecTipoIndice().apply(this);
        }
        outAMultiploSpecTiposIndices(node);
    }

    public void inASpecTipoIndice(ASpecTipoIndice node)
    {
        defaultIn(node);
    }

    public void outASpecTipoIndice(ASpecTipoIndice node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASpecTipoIndice(ASpecTipoIndice node)
    {
        inASpecTipoIndice(node);
        if(node.getInicio() != null)
        {
            node.getInicio().apply(this);
        }
        if(node.getPontoPonto() != null)
        {
            node.getPontoPonto().apply(this);
        }
        if(node.getFim() != null)
        {
            node.getFim().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getIdentificadorTipoOrdinal() != null)
        {
            node.getIdentificadorTipoOrdinal().apply(this);
        }
        outASpecTipoIndice(node);
    }

    public void inAIdentificadorIdentificadorSchemaArray(AIdentificadorIdentificadorSchemaArray node)
    {
        defaultIn(node);
    }

    public void outAIdentificadorIdentificadorSchemaArray(AIdentificadorIdentificadorSchemaArray node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificadorIdentificadorSchemaArray(AIdentificadorIdentificadorSchemaArray node)
    {
        inAIdentificadorIdentificadorSchemaArray(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAIdentificadorIdentificadorSchemaArray(node);
    }

    public void inAArrayIdentificadorSchemaArray(AArrayIdentificadorSchemaArray node)
    {
        defaultIn(node);
    }

    public void outAArrayIdentificadorSchemaArray(AArrayIdentificadorSchemaArray node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayIdentificadorSchemaArray(AArrayIdentificadorSchemaArray node)
    {
        inAArrayIdentificadorSchemaArray(node);
        if(node.getSchemaArray() != null)
        {
            node.getSchemaArray().apply(this);
        }
        outAArrayIdentificadorSchemaArray(node);
    }

    public void inAExistenteTipoResultado(AExistenteTipoResultado node)
    {
        defaultIn(node);
    }

    public void outAExistenteTipoResultado(AExistenteTipoResultado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExistenteTipoResultado(AExistenteTipoResultado node)
    {
        inAExistenteTipoResultado(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAExistenteTipoResultado(node);
    }

    public void inAOrdinalTipoResultado(AOrdinalTipoResultado node)
    {
        defaultIn(node);
    }

    public void outAOrdinalTipoResultado(AOrdinalTipoResultado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrdinalTipoResultado(AOrdinalTipoResultado node)
    {
        inAOrdinalTipoResultado(node);
        if(node.getIdentificadorTipoOrdinal() != null)
        {
            node.getIdentificadorTipoOrdinal().apply(this);
        }
        outAOrdinalTipoResultado(node);
    }

    public void inASentencaComposta(ASentencaComposta node)
    {
        defaultIn(node);
    }

    public void outASentencaComposta(ASentencaComposta node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaComposta(ASentencaComposta node)
    {
        inASentencaComposta(node);
        if(node.getBegin() != null)
        {
            node.getBegin().apply(this);
        }
        if(node.getSequenciaSentencas() != null)
        {
            node.getSequenciaSentencas().apply(this);
        }
        if(node.getEnd() != null)
        {
            node.getEnd().apply(this);
        }
        outASentencaComposta(node);
    }

    public void inAUnicoSequenciaSentencas(AUnicoSequenciaSentencas node)
    {
        defaultIn(node);
    }

    public void outAUnicoSequenciaSentencas(AUnicoSequenciaSentencas node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoSequenciaSentencas(AUnicoSequenciaSentencas node)
    {
        inAUnicoSequenciaSentencas(node);
        if(node.getSentenca() != null)
        {
            node.getSentenca().apply(this);
        }
        outAUnicoSequenciaSentencas(node);
    }

    public void inAMultiploSequenciaSentencas(AMultiploSequenciaSentencas node)
    {
        defaultIn(node);
    }

    public void outAMultiploSequenciaSentencas(AMultiploSequenciaSentencas node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploSequenciaSentencas(AMultiploSequenciaSentencas node)
    {
        inAMultiploSequenciaSentencas(node);
        if(node.getSequenciaSentencas() != null)
        {
            node.getSequenciaSentencas().apply(this);
        }
        if(node.getPontoEVirgula() != null)
        {
            node.getPontoEVirgula().apply(this);
        }
        if(node.getSentenca() != null)
        {
            node.getSentenca().apply(this);
        }
        outAMultiploSequenciaSentencas(node);
    }

    public void inASimplesSentenca(ASimplesSentenca node)
    {
        defaultIn(node);
    }

    public void outASimplesSentenca(ASimplesSentenca node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesSentenca(ASimplesSentenca node)
    {
        inASimplesSentenca(node);
        if(node.getDefinicaoSentencaSimples() != null)
        {
            node.getDefinicaoSentencaSimples().apply(this);
        }
        outASimplesSentenca(node);
    }

    public void inAEstruturadaSentenca(AEstruturadaSentenca node)
    {
        defaultIn(node);
    }

    public void outAEstruturadaSentenca(AEstruturadaSentenca node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEstruturadaSentenca(AEstruturadaSentenca node)
    {
        inAEstruturadaSentenca(node);
        if(node.getDefinicaoSentencaEstruturada() != null)
        {
            node.getDefinicaoSentencaEstruturada().apply(this);
        }
        outAEstruturadaSentenca(node);
    }

    public void inALabelSentenca(ALabelSentenca node)
    {
        defaultIn(node);
    }

    public void outALabelSentenca(ALabelSentenca node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALabelSentenca(ALabelSentenca node)
    {
        inALabelSentenca(node);
        if(node.getLabel() != null)
        {
            node.getLabel().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        outALabelSentenca(node);
    }

    public void inAEmptyLabelSentenca(AEmptyLabelSentenca node)
    {
        defaultIn(node);
    }

    public void outAEmptyLabelSentenca(AEmptyLabelSentenca node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyLabelSentenca(AEmptyLabelSentenca node)
    {
        inAEmptyLabelSentenca(node);
        outAEmptyLabelSentenca(node);
    }

    public void inASimplesDefinicaoSentenca(ASimplesDefinicaoSentenca node)
    {
        defaultIn(node);
    }

    public void outASimplesDefinicaoSentenca(ASimplesDefinicaoSentenca node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesDefinicaoSentenca(ASimplesDefinicaoSentenca node)
    {
        inASimplesDefinicaoSentenca(node);
        if(node.getDefinicaoSentencaSimples() != null)
        {
            node.getDefinicaoSentencaSimples().apply(this);
        }
        outASimplesDefinicaoSentenca(node);
    }

    public void inAEstruturadaDefinicaoSentenca(AEstruturadaDefinicaoSentenca node)
    {
        defaultIn(node);
    }

    public void outAEstruturadaDefinicaoSentenca(AEstruturadaDefinicaoSentenca node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEstruturadaDefinicaoSentenca(AEstruturadaDefinicaoSentenca node)
    {
        inAEstruturadaDefinicaoSentenca(node);
        if(node.getDefinicaoSentencaEstruturada() != null)
        {
            node.getDefinicaoSentencaEstruturada().apply(this);
        }
        outAEstruturadaDefinicaoSentenca(node);
    }

    public void inAEstruturadaFechadaDefinicaoSentenca(AEstruturadaFechadaDefinicaoSentenca node)
    {
        defaultIn(node);
    }

    public void outAEstruturadaFechadaDefinicaoSentenca(AEstruturadaFechadaDefinicaoSentenca node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEstruturadaFechadaDefinicaoSentenca(AEstruturadaFechadaDefinicaoSentenca node)
    {
        inAEstruturadaFechadaDefinicaoSentenca(node);
        if(node.getDefinicaoSentencaEstruturadaFechada() != null)
        {
            node.getDefinicaoSentencaEstruturadaFechada().apply(this);
        }
        outAEstruturadaFechadaDefinicaoSentenca(node);
    }

    public void inASimplesDefinicaoSentencaFechada(ASimplesDefinicaoSentencaFechada node)
    {
        defaultIn(node);
    }

    public void outASimplesDefinicaoSentencaFechada(ASimplesDefinicaoSentencaFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesDefinicaoSentencaFechada(ASimplesDefinicaoSentencaFechada node)
    {
        inASimplesDefinicaoSentencaFechada(node);
        if(node.getDefinicaoSentencaSimples() != null)
        {
            node.getDefinicaoSentencaSimples().apply(this);
        }
        outASimplesDefinicaoSentencaFechada(node);
    }

    public void inAEstruturadaDefinicaoSentencaFechada(AEstruturadaDefinicaoSentencaFechada node)
    {
        defaultIn(node);
    }

    public void outAEstruturadaDefinicaoSentencaFechada(AEstruturadaDefinicaoSentencaFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEstruturadaDefinicaoSentencaFechada(AEstruturadaDefinicaoSentencaFechada node)
    {
        inAEstruturadaDefinicaoSentencaFechada(node);
        if(node.getDefinicaoSentencaEstruturadaFechada() != null)
        {
            node.getDefinicaoSentencaEstruturadaFechada().apply(this);
        }
        outAEstruturadaDefinicaoSentencaFechada(node);
    }

    public void inADefinicaoSentencaSimples(ADefinicaoSentencaSimples node)
    {
        defaultIn(node);
    }

    public void outADefinicaoSentencaSimples(ADefinicaoSentencaSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefinicaoSentencaSimples(ADefinicaoSentencaSimples node)
    {
        inADefinicaoSentencaSimples(node);
        if(node.getLabelSentenca() != null)
        {
            node.getLabelSentenca().apply(this);
        }
        if(node.getSentencaSimples() != null)
        {
            node.getSentencaSimples().apply(this);
        }
        outADefinicaoSentencaSimples(node);
    }

    public void inADefinicaoSentencaEstruturada(ADefinicaoSentencaEstruturada node)
    {
        defaultIn(node);
    }

    public void outADefinicaoSentencaEstruturada(ADefinicaoSentencaEstruturada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefinicaoSentencaEstruturada(ADefinicaoSentencaEstruturada node)
    {
        inADefinicaoSentencaEstruturada(node);
        if(node.getLabelSentenca() != null)
        {
            node.getLabelSentenca().apply(this);
        }
        if(node.getSentencaEstruturada() != null)
        {
            node.getSentencaEstruturada().apply(this);
        }
        outADefinicaoSentencaEstruturada(node);
    }

    public void inADefinicaoSentencaEstruturadaFechada(ADefinicaoSentencaEstruturadaFechada node)
    {
        defaultIn(node);
    }

    public void outADefinicaoSentencaEstruturadaFechada(ADefinicaoSentencaEstruturadaFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefinicaoSentencaEstruturadaFechada(ADefinicaoSentencaEstruturadaFechada node)
    {
        inADefinicaoSentencaEstruturadaFechada(node);
        if(node.getLabelSentenca() != null)
        {
            node.getLabelSentenca().apply(this);
        }
        if(node.getSentencaEstruturadaFechada() != null)
        {
            node.getSentencaEstruturadaFechada().apply(this);
        }
        outADefinicaoSentencaEstruturadaFechada(node);
    }

    public void inAAtribuicaoSentencaSimples(AAtribuicaoSentencaSimples node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoSentencaSimples(AAtribuicaoSentencaSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoSentencaSimples(AAtribuicaoSentencaSimples node)
    {
        inAAtribuicaoSentencaSimples(node);
        if(node.getSentencaAtribuicao() != null)
        {
            node.getSentencaAtribuicao().apply(this);
        }
        outAAtribuicaoSentencaSimples(node);
    }

    public void inAProcedureSentencaSimples(AProcedureSentencaSimples node)
    {
        defaultIn(node);
    }

    public void outAProcedureSentencaSimples(AProcedureSentencaSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedureSentencaSimples(AProcedureSentencaSimples node)
    {
        inAProcedureSentencaSimples(node);
        if(node.getSentencaProcFuncao() != null)
        {
            node.getSentencaProcFuncao().apply(this);
        }
        outAProcedureSentencaSimples(node);
    }

    public void inAGotoSentencaSimples(AGotoSentencaSimples node)
    {
        defaultIn(node);
    }

    public void outAGotoSentencaSimples(AGotoSentencaSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGotoSentencaSimples(AGotoSentencaSimples node)
    {
        inAGotoSentencaSimples(node);
        if(node.getSentencaGoto() != null)
        {
            node.getSentencaGoto().apply(this);
        }
        outAGotoSentencaSimples(node);
    }

    public void inAEmptySentencaSimples(AEmptySentencaSimples node)
    {
        defaultIn(node);
    }

    public void outAEmptySentencaSimples(AEmptySentencaSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptySentencaSimples(AEmptySentencaSimples node)
    {
        inAEmptySentencaSimples(node);
        outAEmptySentencaSimples(node);
    }

    public void inASentencaAtribuicao(ASentencaAtribuicao node)
    {
        defaultIn(node);
    }

    public void outASentencaAtribuicao(ASentencaAtribuicao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaAtribuicao(ASentencaAtribuicao node)
    {
        inASentencaAtribuicao(node);
        if(node.getAcessoVariavel() != null)
        {
            node.getAcessoVariavel().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outASentencaAtribuicao(node);
    }

    public void inASentencaProcFuncao(ASentencaProcFuncao node)
    {
        defaultIn(node);
    }

    public void outASentencaProcFuncao(ASentencaProcFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaProcFuncao(ASentencaProcFuncao node)
    {
        inASentencaProcFuncao(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getParametrosReais() != null)
        {
            node.getParametrosReais().apply(this);
        }
        outASentencaProcFuncao(node);
    }

    public void inAParametrosReais(AParametrosReais node)
    {
        defaultIn(node);
    }

    public void outAParametrosReais(AParametrosReais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametrosReais(AParametrosReais node)
    {
        inAParametrosReais(node);
        if(node.getAbreParenteses() != null)
        {
            node.getAbreParenteses().apply(this);
        }
        if(node.getDefinicaoParametrosReais() != null)
        {
            node.getDefinicaoParametrosReais().apply(this);
        }
        if(node.getFechaParenteses() != null)
        {
            node.getFechaParenteses().apply(this);
        }
        outAParametrosReais(node);
    }

    public void inAEmptyParametrosReais(AEmptyParametrosReais node)
    {
        defaultIn(node);
    }

    public void outAEmptyParametrosReais(AEmptyParametrosReais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyParametrosReais(AEmptyParametrosReais node)
    {
        inAEmptyParametrosReais(node);
        outAEmptyParametrosReais(node);
    }

    public void inAUnicoDefinicaoParametrosReais(AUnicoDefinicaoParametrosReais node)
    {
        defaultIn(node);
    }

    public void outAUnicoDefinicaoParametrosReais(AUnicoDefinicaoParametrosReais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoDefinicaoParametrosReais(AUnicoDefinicaoParametrosReais node)
    {
        inAUnicoDefinicaoParametrosReais(node);
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAUnicoDefinicaoParametrosReais(node);
    }

    public void inAMultiploDefinicaoParametrosReais(AMultiploDefinicaoParametrosReais node)
    {
        defaultIn(node);
    }

    public void outAMultiploDefinicaoParametrosReais(AMultiploDefinicaoParametrosReais node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploDefinicaoParametrosReais(AMultiploDefinicaoParametrosReais node)
    {
        inAMultiploDefinicaoParametrosReais(node);
        if(node.getDefinicaoParametrosReais() != null)
        {
            node.getDefinicaoParametrosReais().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAMultiploDefinicaoParametrosReais(node);
    }

    public void inACompostaSentencaEstruturada(ACompostaSentencaEstruturada node)
    {
        defaultIn(node);
    }

    public void outACompostaSentencaEstruturada(ACompostaSentencaEstruturada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACompostaSentencaEstruturada(ACompostaSentencaEstruturada node)
    {
        inACompostaSentencaEstruturada(node);
        if(node.getSentencaComposta() != null)
        {
            node.getSentencaComposta().apply(this);
        }
        outACompostaSentencaEstruturada(node);
    }

    public void inAWhileSentencaEstruturada(AWhileSentencaEstruturada node)
    {
        defaultIn(node);
    }

    public void outAWhileSentencaEstruturada(AWhileSentencaEstruturada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileSentencaEstruturada(AWhileSentencaEstruturada node)
    {
        inAWhileSentencaEstruturada(node);
        if(node.getSentencaWhile() != null)
        {
            node.getSentencaWhile().apply(this);
        }
        outAWhileSentencaEstruturada(node);
    }

    public void inAIfSentencaEstruturada(AIfSentencaEstruturada node)
    {
        defaultIn(node);
    }

    public void outAIfSentencaEstruturada(AIfSentencaEstruturada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfSentencaEstruturada(AIfSentencaEstruturada node)
    {
        inAIfSentencaEstruturada(node);
        if(node.getSentencaIf() != null)
        {
            node.getSentencaIf().apply(this);
        }
        outAIfSentencaEstruturada(node);
    }

    public void inACompostaSentencaEstruturadaFechada(ACompostaSentencaEstruturadaFechada node)
    {
        defaultIn(node);
    }

    public void outACompostaSentencaEstruturadaFechada(ACompostaSentencaEstruturadaFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACompostaSentencaEstruturadaFechada(ACompostaSentencaEstruturadaFechada node)
    {
        inACompostaSentencaEstruturadaFechada(node);
        if(node.getSentencaComposta() != null)
        {
            node.getSentencaComposta().apply(this);
        }
        outACompostaSentencaEstruturadaFechada(node);
    }

    public void inAWhileSentencaEstruturadaFechada(AWhileSentencaEstruturadaFechada node)
    {
        defaultIn(node);
    }

    public void outAWhileSentencaEstruturadaFechada(AWhileSentencaEstruturadaFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileSentencaEstruturadaFechada(AWhileSentencaEstruturadaFechada node)
    {
        inAWhileSentencaEstruturadaFechada(node);
        if(node.getSentencaWhileFechada() != null)
        {
            node.getSentencaWhileFechada().apply(this);
        }
        outAWhileSentencaEstruturadaFechada(node);
    }

    public void inASentencaWhile(ASentencaWhile node)
    {
        defaultIn(node);
    }

    public void outASentencaWhile(ASentencaWhile node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaWhile(ASentencaWhile node)
    {
        inASentencaWhile(node);
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getDefinicaoSentencaSimples() != null)
        {
            node.getDefinicaoSentencaSimples().apply(this);
        }
        outASentencaWhile(node);
    }

    public void inAEstruturadaSentencaWhile(AEstruturadaSentencaWhile node)
    {
        defaultIn(node);
    }

    public void outAEstruturadaSentencaWhile(AEstruturadaSentencaWhile node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEstruturadaSentencaWhile(AEstruturadaSentencaWhile node)
    {
        inAEstruturadaSentencaWhile(node);
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getDefinicaoSentencaEstruturada() != null)
        {
            node.getDefinicaoSentencaEstruturada().apply(this);
        }
        outAEstruturadaSentencaWhile(node);
    }

    public void inASentencaWhileFechada(ASentencaWhileFechada node)
    {
        defaultIn(node);
    }

    public void outASentencaWhileFechada(ASentencaWhileFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaWhileFechada(ASentencaWhileFechada node)
    {
        inASentencaWhileFechada(node);
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        if(node.getDefinicaoSentencaFechada() != null)
        {
            node.getDefinicaoSentencaFechada().apply(this);
        }
        outASentencaWhileFechada(node);
    }

    public void inASentencaGoto(ASentencaGoto node)
    {
        defaultIn(node);
    }

    public void outASentencaGoto(ASentencaGoto node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaGoto(ASentencaGoto node)
    {
        inASentencaGoto(node);
        if(node.getGoto() != null)
        {
            node.getGoto().apply(this);
        }
        if(node.getLabel() != null)
        {
            node.getLabel().apply(this);
        }
        outASentencaGoto(node);
    }

    public void inASentencaIf(ASentencaIf node)
    {
        defaultIn(node);
    }

    public void outASentencaIf(ASentencaIf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaIf(ASentencaIf node)
    {
        inASentencaIf(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getThen() != null)
        {
            node.getThen().apply(this);
        }
        if(node.getSentenca() != null)
        {
            node.getSentenca().apply(this);
        }
        outASentencaIf(node);
    }

    public void inAElseSentencaIf(AElseSentencaIf node)
    {
        defaultIn(node);
    }

    public void outAElseSentencaIf(AElseSentencaIf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseSentencaIf(AElseSentencaIf node)
    {
        inAElseSentencaIf(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getThen() != null)
        {
            node.getThen().apply(this);
        }
        if(node.getSentencaIfFechada() != null)
        {
            node.getSentencaIfFechada().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getSentenca() != null)
        {
            node.getSentenca().apply(this);
        }
        outAElseSentencaIf(node);
    }

    public void inAIfSentencaIfFechada(AIfSentencaIfFechada node)
    {
        defaultIn(node);
    }

    public void outAIfSentencaIfFechada(AIfSentencaIfFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfSentencaIfFechada(AIfSentencaIfFechada node)
    {
        inAIfSentencaIfFechada(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getThen() != null)
        {
            node.getThen().apply(this);
        }
        if(node.getParteIf() != null)
        {
            node.getParteIf().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getSentencaIfFechada() != null)
        {
            node.getSentencaIfFechada().apply(this);
        }
        outAIfSentencaIfFechada(node);
    }

    public void inASentencaIfFechada(ASentencaIfFechada node)
    {
        defaultIn(node);
    }

    public void outASentencaIfFechada(ASentencaIfFechada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASentencaIfFechada(ASentencaIfFechada node)
    {
        inASentencaIfFechada(node);
        if(node.getDefinicaoSentencaFechada() != null)
        {
            node.getDefinicaoSentencaFechada().apply(this);
        }
        outASentencaIfFechada(node);
    }

    public void inAAcessoVariavel(AAcessoVariavel node)
    {
        defaultIn(node);
    }

    public void outAAcessoVariavel(AAcessoVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcessoVariavel(AAcessoVariavel node)
    {
        inAAcessoVariavel(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAAcessoVariavel(node);
    }

    public void inAIndexadaAcessoVariavel(AIndexadaAcessoVariavel node)
    {
        defaultIn(node);
    }

    public void outAIndexadaAcessoVariavel(AIndexadaAcessoVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIndexadaAcessoVariavel(AIndexadaAcessoVariavel node)
    {
        inAIndexadaAcessoVariavel(node);
        if(node.getVariavelIndexada() != null)
        {
            node.getVariavelIndexada().apply(this);
        }
        outAIndexadaAcessoVariavel(node);
    }

    public void inAVariavelIndexada(AVariavelIndexada node)
    {
        defaultIn(node);
    }

    public void outAVariavelIndexada(AVariavelIndexada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelIndexada(AVariavelIndexada node)
    {
        inAVariavelIndexada(node);
        if(node.getAcessoVariavel() != null)
        {
            node.getAcessoVariavel().apply(this);
        }
        if(node.getAbreColchete() != null)
        {
            node.getAbreColchete().apply(this);
        }
        if(node.getExpressoes() != null)
        {
            node.getExpressoes().apply(this);
        }
        if(node.getFechaColchete() != null)
        {
            node.getFechaColchete().apply(this);
        }
        outAVariavelIndexada(node);
    }

    public void inAUnicoExpressoes(AUnicoExpressoes node)
    {
        defaultIn(node);
    }

    public void outAUnicoExpressoes(AUnicoExpressoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoExpressoes(AUnicoExpressoes node)
    {
        inAUnicoExpressoes(node);
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAUnicoExpressoes(node);
    }

    public void inAMultiploExpressoes(AMultiploExpressoes node)
    {
        defaultIn(node);
    }

    public void outAMultiploExpressoes(AMultiploExpressoes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploExpressoes(AMultiploExpressoes node)
    {
        inAMultiploExpressoes(node);
        if(node.getExpressoes() != null)
        {
            node.getExpressoes().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAMultiploExpressoes(node);
    }

    public void inAExpressao(AExpressao node)
    {
        defaultIn(node);
    }

    public void outAExpressao(AExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressao(AExpressao node)
    {
        inAExpressao(node);
        if(node.getExpressaoSimples() != null)
        {
            node.getExpressaoSimples().apply(this);
        }
        if(node.getExpressaoRelacional() != null)
        {
            node.getExpressaoRelacional().apply(this);
        }
        outAExpressao(node);
    }

    public void inAExpressaoRelacional(AExpressaoRelacional node)
    {
        defaultIn(node);
    }

    public void outAExpressaoRelacional(AExpressaoRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressaoRelacional(AExpressaoRelacional node)
    {
        inAExpressaoRelacional(node);
        if(node.getOperadorRelacional() != null)
        {
            node.getOperadorRelacional().apply(this);
        }
        if(node.getExpressaoSimples() != null)
        {
            node.getExpressaoSimples().apply(this);
        }
        outAExpressaoRelacional(node);
    }

    public void inAEmptyExpressaoRelacional(AEmptyExpressaoRelacional node)
    {
        defaultIn(node);
    }

    public void outAEmptyExpressaoRelacional(AEmptyExpressaoRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyExpressaoRelacional(AEmptyExpressaoRelacional node)
    {
        inAEmptyExpressaoRelacional(node);
        outAEmptyExpressaoRelacional(node);
    }

    public void inAUnicoComSinalExpressaoSimples(AUnicoComSinalExpressaoSimples node)
    {
        defaultIn(node);
    }

    public void outAUnicoComSinalExpressaoSimples(AUnicoComSinalExpressaoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoComSinalExpressaoSimples(AUnicoComSinalExpressaoSimples node)
    {
        inAUnicoComSinalExpressaoSimples(node);
        {
            List<TSinal> copy = new ArrayList<TSinal>(node.getSinal());
            for(TSinal e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAUnicoComSinalExpressaoSimples(node);
    }

    public void inAUnicoSemSinalExpressaoSimples(AUnicoSemSinalExpressaoSimples node)
    {
        defaultIn(node);
    }

    public void outAUnicoSemSinalExpressaoSimples(AUnicoSemSinalExpressaoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoSemSinalExpressaoSimples(AUnicoSemSinalExpressaoSimples node)
    {
        inAUnicoSemSinalExpressaoSimples(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAUnicoSemSinalExpressaoSimples(node);
    }

    public void inAMultiploSemSinalExpressaoSimples(AMultiploSemSinalExpressaoSimples node)
    {
        defaultIn(node);
    }

    public void outAMultiploSemSinalExpressaoSimples(AMultiploSemSinalExpressaoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploSemSinalExpressaoSimples(AMultiploSemSinalExpressaoSimples node)
    {
        inAMultiploSemSinalExpressaoSimples(node);
        if(node.getExpressaoSimples() != null)
        {
            node.getExpressaoSimples().apply(this);
        }
        if(node.getOperadorAditivo() != null)
        {
            node.getOperadorAditivo().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAMultiploSemSinalExpressaoSimples(node);
    }

    public void inAMultiploComSinalExpressaoSimples(AMultiploComSinalExpressaoSimples node)
    {
        defaultIn(node);
    }

    public void outAMultiploComSinalExpressaoSimples(AMultiploComSinalExpressaoSimples node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploComSinalExpressaoSimples(AMultiploComSinalExpressaoSimples node)
    {
        inAMultiploComSinalExpressaoSimples(node);
        if(node.getExpressaoSimples() != null)
        {
            node.getExpressaoSimples().apply(this);
        }
        if(node.getOperadorAditivo() != null)
        {
            node.getOperadorAditivo().apply(this);
        }
        {
            List<TSinal> copy = new ArrayList<TSinal>(node.getSinal());
            for(TSinal e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAMultiploComSinalExpressaoSimples(node);
    }

    public void inAUnicoTermo(AUnicoTermo node)
    {
        defaultIn(node);
    }

    public void outAUnicoTermo(AUnicoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoTermo(AUnicoTermo node)
    {
        inAUnicoTermo(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAUnicoTermo(node);
    }

    public void inAMultiploTermo(AMultiploTermo node)
    {
        defaultIn(node);
    }

    public void outAMultiploTermo(AMultiploTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploTermo(AMultiploTermo node)
    {
        inAMultiploTermo(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getOperadorMultiplicativo() != null)
        {
            node.getOperadorMultiplicativo().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAMultiploTermo(node);
    }

    public void inAConstanteSemSinalFator(AConstanteSemSinalFator node)
    {
        defaultIn(node);
    }

    public void outAConstanteSemSinalFator(AConstanteSemSinalFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstanteSemSinalFator(AConstanteSemSinalFator node)
    {
        inAConstanteSemSinalFator(node);
        if(node.getConstanteSemSinal() != null)
        {
            node.getConstanteSemSinal().apply(this);
        }
        outAConstanteSemSinalFator(node);
    }

    public void inAExpressaoFator(AExpressaoFator node)
    {
        defaultIn(node);
    }

    public void outAExpressaoFator(AExpressaoFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressaoFator(AExpressaoFator node)
    {
        inAExpressaoFator(node);
        if(node.getAbreParenteses() != null)
        {
            node.getAbreParenteses().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getFechaParenteses() != null)
        {
            node.getFechaParenteses().apply(this);
        }
        outAExpressaoFator(node);
    }

    public void inANotFator(ANotFator node)
    {
        defaultIn(node);
    }

    public void outANotFator(ANotFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotFator(ANotFator node)
    {
        inANotFator(node);
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outANotFator(node);
    }

    public void inAFuncaoOuVariavelFator(AFuncaoOuVariavelFator node)
    {
        defaultIn(node);
    }

    public void outAFuncaoOuVariavelFator(AFuncaoOuVariavelFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoOuVariavelFator(AFuncaoOuVariavelFator node)
    {
        inAFuncaoOuVariavelFator(node);
        if(node.getSentencaProcFuncao() != null)
        {
            node.getSentencaProcFuncao().apply(this);
        }
        outAFuncaoOuVariavelFator(node);
    }

    public void inAVarIndexadaFator(AVarIndexadaFator node)
    {
        defaultIn(node);
    }

    public void outAVarIndexadaFator(AVarIndexadaFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarIndexadaFator(AVarIndexadaFator node)
    {
        inAVarIndexadaFator(node);
        if(node.getVariavelIndexada() != null)
        {
            node.getVariavelIndexada().apply(this);
        }
        outAVarIndexadaFator(node);
    }

    public void inAMenorOperadorRelacional(AMenorOperadorRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorOperadorRelacional(AMenorOperadorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorOperadorRelacional(AMenorOperadorRelacional node)
    {
        inAMenorOperadorRelacional(node);
        if(node.getMenor() != null)
        {
            node.getMenor().apply(this);
        }
        outAMenorOperadorRelacional(node);
    }

    public void inAMenorIgualOperadorRelacional(AMenorIgualOperadorRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualOperadorRelacional(AMenorIgualOperadorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualOperadorRelacional(AMenorIgualOperadorRelacional node)
    {
        inAMenorIgualOperadorRelacional(node);
        if(node.getMenorIgual() != null)
        {
            node.getMenorIgual().apply(this);
        }
        outAMenorIgualOperadorRelacional(node);
    }

    public void inAMaiorOperadorRelacional(AMaiorOperadorRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorOperadorRelacional(AMaiorOperadorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorOperadorRelacional(AMaiorOperadorRelacional node)
    {
        inAMaiorOperadorRelacional(node);
        if(node.getMaior() != null)
        {
            node.getMaior().apply(this);
        }
        outAMaiorOperadorRelacional(node);
    }

    public void inAMaiorIgualOperadorRelacional(AMaiorIgualOperadorRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualOperadorRelacional(AMaiorIgualOperadorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualOperadorRelacional(AMaiorIgualOperadorRelacional node)
    {
        inAMaiorIgualOperadorRelacional(node);
        if(node.getMaiorIgual() != null)
        {
            node.getMaiorIgual().apply(this);
        }
        outAMaiorIgualOperadorRelacional(node);
    }

    public void inAIgualOperadorRelacional(AIgualOperadorRelacional node)
    {
        defaultIn(node);
    }

    public void outAIgualOperadorRelacional(AIgualOperadorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualOperadorRelacional(AIgualOperadorRelacional node)
    {
        inAIgualOperadorRelacional(node);
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        outAIgualOperadorRelacional(node);
    }

    public void inADiferenteOperadorRelacional(ADiferenteOperadorRelacional node)
    {
        defaultIn(node);
    }

    public void outADiferenteOperadorRelacional(ADiferenteOperadorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADiferenteOperadorRelacional(ADiferenteOperadorRelacional node)
    {
        inADiferenteOperadorRelacional(node);
        if(node.getDiferente() != null)
        {
            node.getDiferente().apply(this);
        }
        outADiferenteOperadorRelacional(node);
    }

    public void inASomaSubOperadorAditivo(ASomaSubOperadorAditivo node)
    {
        defaultIn(node);
    }

    public void outASomaSubOperadorAditivo(ASomaSubOperadorAditivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaSubOperadorAditivo(ASomaSubOperadorAditivo node)
    {
        inASomaSubOperadorAditivo(node);
        if(node.getSinal() != null)
        {
            node.getSinal().apply(this);
        }
        outASomaSubOperadorAditivo(node);
    }

    public void inAOrOperadorAditivo(AOrOperadorAditivo node)
    {
        defaultIn(node);
    }

    public void outAOrOperadorAditivo(AOrOperadorAditivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrOperadorAditivo(AOrOperadorAditivo node)
    {
        inAOrOperadorAditivo(node);
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        outAOrOperadorAditivo(node);
    }

    public void inAMultiplicacaoOperadorMultiplicativo(AMultiplicacaoOperadorMultiplicativo node)
    {
        defaultIn(node);
    }

    public void outAMultiplicacaoOperadorMultiplicativo(AMultiplicacaoOperadorMultiplicativo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplicacaoOperadorMultiplicativo(AMultiplicacaoOperadorMultiplicativo node)
    {
        inAMultiplicacaoOperadorMultiplicativo(node);
        if(node.getMultiplicacao() != null)
        {
            node.getMultiplicacao().apply(this);
        }
        outAMultiplicacaoOperadorMultiplicativo(node);
    }

    public void inADivisaoOperadorMultiplicativo(ADivisaoOperadorMultiplicativo node)
    {
        defaultIn(node);
    }

    public void outADivisaoOperadorMultiplicativo(ADivisaoOperadorMultiplicativo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoOperadorMultiplicativo(ADivisaoOperadorMultiplicativo node)
    {
        inADivisaoOperadorMultiplicativo(node);
        if(node.getDivisao() != null)
        {
            node.getDivisao().apply(this);
        }
        outADivisaoOperadorMultiplicativo(node);
    }

    public void inAAndOperadorMultiplicativo(AAndOperadorMultiplicativo node)
    {
        defaultIn(node);
    }

    public void outAAndOperadorMultiplicativo(AAndOperadorMultiplicativo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndOperadorMultiplicativo(AAndOperadorMultiplicativo node)
    {
        inAAndOperadorMultiplicativo(node);
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        outAAndOperadorMultiplicativo(node);
    }

    public void inADivOperadorMultiplicativo(ADivOperadorMultiplicativo node)
    {
        defaultIn(node);
    }

    public void outADivOperadorMultiplicativo(ADivOperadorMultiplicativo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivOperadorMultiplicativo(ADivOperadorMultiplicativo node)
    {
        inADivOperadorMultiplicativo(node);
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        outADivOperadorMultiplicativo(node);
    }

    public void inAModOperadorMultiplicativo(AModOperadorMultiplicativo node)
    {
        defaultIn(node);
    }

    public void outAModOperadorMultiplicativo(AModOperadorMultiplicativo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModOperadorMultiplicativo(AModOperadorMultiplicativo node)
    {
        inAModOperadorMultiplicativo(node);
        if(node.getMod() != null)
        {
            node.getMod().apply(this);
        }
        outAModOperadorMultiplicativo(node);
    }
}
